quarkus-qe/beefy-scenarios

.github/workflows/daily.yaml
Ignore 004-quarkus-HHH-and-HV in native mode as H2 server can't be embeded in native image
=> Ignore 004-quarkus-HHH-and-HV in native mode as H2 server can't be embeded in native image

007-openshift-yaml-health-probes/pom.xml, 007-openshift-yaml-health-probes/src/main/java/io/quarkus/qe/openshift/GreetingResource.java, 007-openshift-yaml-health-probes/src/main/resources/application.properties, 007-openshift-yaml-health-probes/src/test/java/io/quarkus/qe/openshift/OpenShiftYamlHealthProbesIT.java, pom.xml
OpenShift yaml health probes with custom image name
Test is using `quarkus-openshift` extension and not the kubernetes one.
=> OpenShift yaml health probes with custom image name

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Move to newer version of joschi/setup-jdk to be in sync with version used in Quarkus master
=> Move to newer version of joschi/setup-jdk to be in sync with version used in Quarkus master

002-quarkus-all-extensions/pom.xml
Remove universe extensions, we cover core ones, we do not need to handle external extensions
Those extensions are troublesome, just filed issues for Cassandra and Outbox
=> Remove universe extensions, we cover core ones, we do not need to handle external extensions

002-quarkus-all-extensions/pom.xml
quarkus-hibernate-search-elasticsearch was renamed to quarkus-hibernate-search-orm-elasticsearch
done in #12790 in https://github.com/quarkusio/quarkus
=> quarkus-hibernate-search-elasticsearch was renamed to quarkus-hibernate-search-orm-elasticsearch

010-quarkus-opentracing-reactive-grpc/README.md, 010-quarkus-opentracing-reactive-grpc/pom.xml, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/ping/GrpcPingResource.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/ping/PingResource.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/ping/ReactivePingResource.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/ping/clients/PongClient.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/ping/clients/ReactivePongClient.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/pong/GrpcPongService.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/pong/PongResource.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/pong/ReactivePongResource.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/traceable/TraceableResource.java, 010-quarkus-opentracing-reactive-grpc/src/main/proto/pong.proto, 010-quarkus-opentracing-reactive-grpc/src/main/resources/application.properties, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/AbstractPingPongResourceTest.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/GrpcPingPongResourceTest.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/NativeReactivePingPongResourceIT.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/NativeRestPingPongResourceIT.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/ReactivePingPongResourceTest.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/RestPingPongResourceTest.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/containers/JaegerTestResource.java
Module that test whether the OpenTracing data is transmitted among services.
There are two applications:
- Ping application that will invoke the Pong application using the RestClient and will return the expected "ping pong" output.
- Pong application that will return the "pong" output.
We're covering:
- Among REST services
- Among Reactive services
- With REST service to gRPC (this is not working... should be an issue? If not, I guess we should delete this).
Note that we don't need a running Jaeger to see this functionality working. This was odd to me at first and perhaps we should verify that indeed Jaeger is getting the metrics. Let me know your thoughts about this. @rsvoboda @mjurc
=> Added opentracing, resteasy, mutiny example

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Use Google mirror when building Quarkus master to avoid connection reset from central
50% of runs in https://github.com/quarkus-qe/beefy-scenarios/actions failed in last couple of days because of connection reset received from central
=> Use Google mirror when building Quarkus master to avoid connection reset from central

011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ApplicationEntity.java, 011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/VersionEntity.java, 011-quarkus-panache-rest-flyway/src/main/resources/db/migration/V1.0.1__entity_with_id_varchar.sql, 011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java
Added a new check to cover the many-to-one relationship in the Panache REST flyway module.
=> panache-rest-flyway: add many-to-one relationship with string id

001-quarkus-getting-started/src/main/java/io/quarkus/qe/core/GreetingResource.java
TD for https://issues.redhat.com/browse/QUARKUS-533
Check that java.lang annotations are allowed in resource prefix
=> Add Deprecated annotation to JaxRs resource

011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ApplicationEntity.java, 011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ApplicationQueryResource.java, 011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ServiceEntity.java, 011-quarkus-panache-rest-flyway/src/main/resources/db/migration/V1.0.2__add_service.sql, 011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java
The objective of these changes is to coverage the `@Filter` and reproduce the missing functionality to use `@FilterJoinTable` (reported by https://github.com/quarkusio/quarkus/issues/13831).
=> Add filters coverage in panache-rest module

601-spring-data-primitive-types/README.md, 601-spring-data-primitive-types/pom.xml, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/HttpCommonsHeaders.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/SessionResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/AppConfiguration.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/CounterBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/InstanceIdBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/RequestIdBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/SessionIdBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Address.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Animal.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Book.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Cat.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Mammal.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/NamedEntity.java, 601-spring-data-primitive-types/src/main/resources/import.sql, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/BookResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersIT.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java
Issues References:
-----------------------------
[Fix spring-data-jpa field lookup with layered @MappedSuperclasses](https://issues.redhat.com/browse/QUARKUS-532)
[Make embedded fields with camel-case work in Spring Data JPA repositories](https://issues.redhat.com/browse/QUARKUS-525)
[Spring's @Scope#scopeName is now taken into account](https://issues.redhat.com/browse/QUARKUS-547)
We have added a "super" structure over the existing Cat entity. With the current implementation Cats extends Mammal and mammal are animals.
We've created a query over an embedded camelCase field.
We've created an HTTP Request filter in order to add headers to the response:
- x-session: Keep the same value per HTTP session
- x-count: count the number of requests
- x-request: increase his value per request
- …
=> Spring beans and JPA test coverage

302-quarkus-vertx-jwt/README.md, 302-quarkus-vertx-jwt/pom.xml
A valid `quarkus.package.type` must be provided. 
Error: [error]: Build step io.quarkus.deployment.pkg.steps.PackageTypeVerificationBuildStep#verify threw an exception: java.lang.IllegalStateException: Unknown packaging type none known types are [fast-jar, legacy, native, jar, uber-jar, mutable-jar]
**Doc:** [Valid package types](https://quarkus.io/guides/all-config#quarkus-core_quarkus.package.type)
=> fix: remove quarkus.package.type = none from pom.xml

302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/resources/RedisResource.java, pom.xml
Vertx/jwt-redis: move on to quay.io docker registry.
=> vertx/jwt-redis move on to quay.io docker registry

015-quarkus-micrometer/README.md, 015-quarkus-micrometer/pom.xml, 015-quarkus-micrometer/src/main/java/io/quarkus/qe/UsingMicroProfilePingPongResource.java, 015-quarkus-micrometer/src/main/java/io/quarkus/qe/UsingRegistryPingPongResource.java, 015-quarkus-micrometer/src/main/resources/application.properties, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/NativeUsingMicroProfilePingPongResourceIT.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/NativeUsingRegistryPingPongResourceIT.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/UsingMicroProfilePingPongResourceTest.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/UsingRegistryPingPongResourceTest.java, pom.xml
Module that covers the Micrometer extension usage via `MeterRegistry` and `MicroProfile API` approaches. Both will use a counter metrics for testing purposes. 
The `MeterRegistry` approach includes three scenarios: 
- `simple`: single call will increment the counter.
- `forloop`: will increment the counter a number of times.
- `forloop parallel`: will increment the counter a number of times using a parallel flow.
The `MicroProfile API` approach will include only the `simple` scenario.   
Note that more complex scenarios such as the integration with either Kafka and Prometheus are out of scope for this PR.
=> Add micrometer scenarios

pom.xml
Bump testcontainers version to 1.15.1
We had failure https://github.com/quarkus-qe/beefy-scenarios/actions/runs/535412868 in nightly runs.
This should be fixed in 1.15.1.
We do not have so many modules as in QS so I'm not afraid of the stuck threads / execution here.
=> Bump testcontainers version to 1.15.1

015-quarkus-micrometer/README.md, 015-quarkus-micrometer/src/main/java/io/quarkus/qe/WithoutCustomMetricsPingPongResource.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/HttpServerMetricsTest.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/NativeHttpServerMetricsIT.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/UsingMicroProfilePingPongResourceTest.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/UsingRegistryPingPongResourceTest.java
These metrics can be disabled with `https://quarkus.io/guides/micrometer#quarkus-micrometer_quarkus.micrometer.binder.vertx.enabled`. I've already reported an issue because it's the HTTP server metrics, instead of purely vertx metrics: https://github.com/quarkusio/quarkus/issues/14745
=> Add Http Server Metrics scenario

002-quarkus-all-extensions/pom.xml
The build was failing with the next exception:
```
[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.RuntimeException: Extensions with conflicting package types. One extension requires uber-jar another requires legacy format
```
The extension that was using the legacy package is amazon-lambda-common and hence removing it.
=> Remove Amazon Lambda Common due to legacy package

.github/workflows/pr.yaml
The quickly property is being used in the daily workflows. 
Note that there is a way to make the Quarkus build even faster:
```
git clone https://github.com/quarkusio/quarkus.git && cd quarkus 
&& mvn -B -s .github/mvn-settings.xml clean install -Dquickly -f bom/application 
&& mvn -B -s .github/mvn-settings.xml clean install -Dquickly -f bom/test 
&& mvn -B -s .github/mvn-settings.xml clean install -Dquickly -f build-parent 
&& mvn -B -s .github/mvn-settings.xml clean install -Dquickly -f core 
&& mvn -B -s .github/mvn-settings.xml clean install -Dquickly -f extensions 
&& mvn -B -s .github/mvn-settings.xml clean install -Dquickly -f test-framework
```
I've tested the above command and improves the time build from 15 min to 5 min. So, it works like a charm, but it's ugly like a ñu and …
=> Use quickly parameter for faster Quarkus builds

018-quarkus-runtime-properties/README.md, 018-quarkus-runtime-properties/pom.xml, 018-quarkus-runtime-properties/src/main/resources/application.properties, 018-quarkus-runtime-properties/src/test/java/io/quarkus/qe/toggle/BaseTogglablePropertiesTest.java, 018-quarkus-runtime-properties/src/test/java/io/quarkus/qe/toggle/TogglablePropertiesOnDevModeTest.java, 018-quarkus-runtime-properties/src/test/java/io/quarkus/qe/toggle/TogglablePropertiesOnJvmModeTest.java, 018-quarkus-runtime-properties/src/test/java/io/quarkus/qe/toggle/TogglablePropertiesOnNativeModeIT.java, 018-quarkus-runtime-properties/src/test/java/io/quarkus/qe/toggle/TogglableServices.java, pom.xml
Module that covers the runtime configuration to ensure the changes take effect. The configuration that is covered is:
- Allow disabling/enabling `Swagger/GraphQL/Heatlh/OpenAPI` endpoints on DEV mode
=> Add scenario for runtime properties

019-quarkus-consul/src/test/java/io/quarkus/qe/containers/ConsulContainer.java, 019-quarkus-consul/src/test/java/io/quarkus/qe/containers/ConsulTestResource.java
Using network=host is not compatible with Windows and MacOS.
Using the latest image of Consul allows running consul without network=host, just mapping the port.
=> Fix consul test for windows and macos

020-quarkus-http-non-application-endpoints/README.md, 020-quarkus-http-non-application-endpoints/pom.xml, 020-quarkus-http-non-application-endpoints/src/main/java/io/quarkus/qe/http/non_application/endpoint/HelloResource.java, 020-quarkus-http-non-application-endpoints/src/main/resources/application.properties, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/BackwardCompatibilityIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/BackwardCompatibilityTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/CommonNonAppEndpoint.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointNonRootPathIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointNonRootPathTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTestNonBaseRootPathIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTestNonBaseRootPathTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/RelativePathNonAppEndpointIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/RelativePathNonAppEndpointTest.java, pom.xml
This PR cover non-application endpoint behavior:
* Relative paths: 
```
quarkus.http.root-path=/api
quarkus.http.non-application-root-path=q
quarkus.http.redirect-to-non-application-root-path=false
```
Valid request example: `http://localhost:8080/api/q/health`
* Empty non-application root path:
```
quarkus.http.root-path=/api
quarkus.http.non-application-root-path=/
quarkus.http.redirect-to-non-application-root-path=false
```
All request will return an HTTP status `404`
* Non-application root path with `slash` base path:
```
%emptyRootPath.quarkus.http.root-path=/
%emptyRootPath.quarkus.http.non-application-root-path=/q
%emptyRootPath.quarkus.http.redirect-to-non-application-root-path=false
```
Valid request example: `http://localhost:8080/q/health`
* Defined application base path and …
=> Non-appliaction endpoints coverage

601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/HttpCommonsHeaders.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Address.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Animal.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Book.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Mammal.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/MapStringConverter.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/NamedEntity.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/BookResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java
The aim of this PR is to cover JPA `convert` annotation, motivated by this [issue](https://github.com/quarkusio/quarkus/issues/13234)
We have created a new field over the `Book` entity called `comments`. The type of this field is a `mutable type (a Map)`, and is converted to a JSON String through a JPA `convert` annotation.
=> JPA mapping values coverage

.github/workflows/daily.yaml, Jenkinsfile, pom.xml
This PR is motivated because we can't exclude modules via Maven argument for the Quarkus ecosystem.
=> Disable 002 module in Native

304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/BasicsRouteHandler.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/BasicsRouteHandlerTest.java
It seems that hyphens are not legal, but we can change the method to use underscore. 
I've added another scenario for a new issue.
=> Remove workaround for Vert.x Params param underscore

304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/BasicsRouteHandler.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/BasicsRouteHandlerTest.java
The resolution from https://github.com/quarkusio/quarkus/issues/15470 was to avoid having routes that do not return anything. So, if the app spots a route of this kind, the app will crash because of validation error at startup. Hence, we need to remove this route now.
=> Remove invalid Vert.x route to prevent app starts

020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/BackwardCompatibilityIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/BackwardCompatibilityTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/CommonNonAppEndpoint.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointNonRootPathIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointNonRootPathTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTestNonBaseRootPathIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTestNonBaseRootPathTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/RelativePathNonAppEndpointIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/RelativePathNonAppEndpointTest.java, pom.xml
When you are running your test, using `QuarkusProdModeTest` you should avoid using `@NativeImageTest` annotation, otherwise, you will have a collision between ports. because `@NativeImageTest` will launch an app over port 8081 and `QuarkusProdModeTest` will launch another app per test, over the same port. 
We have defined a 'quarkus.profile' system property on `maven-failsafe-plugin`. Based on this property, we will build a native image or a JVM instance.
=> Avoid ports collision in 020-quarkus-http-non-application-endpoints for native mode

013-quarkus-oidc-restclient/src/main/resources/application.properties, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/AbstractPingPongResourceTest.java
Adding timeout using Rest Assured for the Module 013. This is motivated because it failed in Jenkins when verifying Quarkus 1.11.5:
```
15:09:08 [INFO] -------------< io.quarkus.qe:013-quarkus-oidc-restclient >--------------
15:09:08 [INFO] Building 013-quarkus-oidc-restclient 1.0.0-SNAPSHOT              [14/27]
15:09:08 [INFO] --------------------------------[ jar ]---------------------------------
15:09:08 [INFO] 
15:09:08 [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ 013-quarkus-oidc-restclient ---
15:09:08 [INFO] 
15:09:08 [INFO] --- quarkus-maven-plugin:1.11.5.Final-redhat-00006:generate-code (default) @ 013-quarkus-oidc-restclient ---
15:09:08 [INFO] Downloading from libs-snapshot-local: http://10.0.139.54:8040/artifactory/libs-snapshot-local/io/quarkus/qe/013-quarkus-oid …
```
=> Add timeouts for Module 013

.github/workflows/daily.yaml
After https://github.com/graalvm/mandrel/issues/218#issuecomment-792832701 has been fixed and new images have been populated, this PR is about to reenable the mandrel image.
=> Configure mandrel image for daily builds

004-quarkus-HHH-and-HV/README.md, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Account.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Customer.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Item.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/ItemsResource.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Role.java, 004-quarkus-HHH-and-HV/src/main/resources/application.properties, 004-quarkus-HHH-and-HV/src/main/resources/import.sql, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/items/ItemsResourceTest.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/items/NativeItemsResourceIT.java
Added coverage for issues:
- https://github.com/quarkusio/quarkus/issues/14201
- https://github.com/quarkusio/quarkus/issues/14881
Note that this solution is based on the reproducer provided in one of the above issues: https://github.com/yntelectual/quarkus-bug-14201
I verified that the new test does not work if we run it with 1.11.1.Final (as an example):
```
mvn clean install -Dquarkus-plugin.version=1.11.1.Final -Dquarkus.platform.version=1.11.1.Final
``` 
As expected, It fails with:
```
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "email" of relation "account" violates not-null constraint
Detail: Failing row contains (1, null, null).
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
at …
```
=> [Master] Updated module 004 module to reproduce data loss issues

003-quarkus-many-extensions/pom.xml
quarkus-kubernetes is pulling a lot of io.fabric8 dependencies, 4g is not enough for native compilation
=> quarkus-kubernetes is pulling a lot of io.fabric8 dependencies, 4g is not enough for native compilation

011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/BookRepositoryTest.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/LibraryRepositoryTest.java
The issue https://github.com/quarkusio/quarkus/issues/15492#event-4450469504 has been resolved, so we need to enable back the coverage to cover this functionality.
=> [master] Enable tests to cover validation for Panache and Spring REST

003-quarkus-many-extensions/pom.xml
Upstream is fixed, revert "quarkus-kubernetes is pulling a lot of iofabric8 dependencies, 4g is not enough for native compilation"
This reverts commit 0eccc99e2081695b49fe99d59dee56f02a6fb451.
=> Upstream is fixed, revert "quarkus-kubernetes is pulling a lot of iofabric8 dependencies, 4g is not enough for native compilation"

603-spring-web-smallrye-openapi/src/test/resources/request-types.csv, 603-spring-web-smallrye-openapi/src/test/resources/response-types.csv
Revert "Spring Web + Smallrye OpenAPI coverage - failing cases commented out".
Related to https://github.com/quarkus-qe/beefy-scenarios/pull/120.
This reverts commit 8c299b1447bab2dbf9a690f4b25af25609f89ad9.
=> Revert "Spring Web + Smallrye OpenAPI coverage - failing cases"

004-quarkus-HHH-and-HV/README.md, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBean.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBeanResource.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/transaction/NativeTransactionScopeBeanResourceIT.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBeanResourceTest.java
Reproducer for https://issues.redhat.com/browse/QUARKUS-661. This was fixed in 1.11 as part of this PR: https://github.com/quarkusio/quarkus/pull/14053, but there was missing coverage for Native tests which was the motivation for this PR. 
When running the module 004 using:
```
mvn clean verify -Dtest=TransactionScopeBeanResourceTest
```
As expected, it will fail with:
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.936 s <<< FAILURE! - in io.quarkus.qe.hibernate.transaction.TransactionScopeBeanResourceTest
[ERROR] shouldPostConstructAndPreDestroyBeInvoked  Time elapsed: 1.6 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: PostConstruct method is not invoked ==> expected: <true> but was: <false>
at …
```
=> Added reproducer for QUARKUS-661

009-quarkus-infinispan-grpc-kafka/src/main/resources/application.properties
When we are running some test in Upstream, there is a port collision with GRPC .
Pickup [suggested changes](https://github.com/quarkusio/quarkus/issues/15934)
=> Fix grpc port collision on test

009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/BlockingHelloService.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/GreetingResource.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/MutinyHelloService.java, 009-quarkus-infinispan-grpc-kafka/src/main/proto/dto.proto, 009-quarkus-infinispan-grpc-kafka/src/main/proto/helloworld_blocking.proto, 009-quarkus-infinispan-grpc-kafka/src/main/proto/helloworld_mutiny.proto
Refactor .proto files in order to avoid service names colissions:
Error example:
```
java.lang.IllegalStateException: Duplicated gRPC service: helloworld.Greeter
```
=> Avoid mutiny/blocking grpc be under the same service in order to avoid service.name collisions.

022-quarkus-properties-config-all/.env, 022-quarkus-properties-config-all/README.md, 022-quarkus-properties-config-all/pom.xml, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/GreetingResource.java, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/config/AntagonistConfiguration.java, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/config/ProtagonistConfiguration.java, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/config/interfaces/IBiography.java, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/config/interfaces/ProtagonistConfigurable.java, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/converter/CustomEmailConverter.java, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/converter/KrustyEmail.java, 022-quarkus-properties-config-all/src/main/java/quarkus/qe/providers/CustomConfigSource.java, 022-quarkus-properties-config-all/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource, 022-quarkus-properties-config-all/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter, 022-quarkus-properties-config-all/src/main/resources/application.properties, 022-quarkus-properties-config-all/src/main/resources/application.yaml, 022-quarkus-properties-config-all/src/main/resources/configsource.properties, 022-quarkus-properties-config-all/src/main/resources/resources-config.json, 022-quarkus-properties-config-all/src/test/java/quarkus/qe/config/VariousConfigurationSourcesTest.java, 022-quarkus-properties-config-all/src/test/java/quarkus/qe/config/VariousConfigurationSourcesTestIT.java, pom.xml
This test covers most of the config properties for Quarkus described in Configuring you Quarkus application guide
https://access.redhat.com/documentation/en-us/red_hat_build_of_quarkus/1.7/html-single/configuring_your_quarkus_applications/index
resources-config.json file should be there according to https://quarkus.io/guides/writing-native-applications-tips#supporting-native-in-your-application (without it, the errors are thrown on the following line
`InputStream in = CustomConfigSource.class.getResourceAsStream(PROPERTIES_FILE);`
)
Module has reach README file
=> Add test to cover Quarkus configuration properties

012-quarkus-kafka-streams/src/main/resources/application.properties, 012-quarkus-kafka-streams/src/test/resources/application.properties
Currently, we are not setting any `kafka-streams.commit.interval.ms` so looks like by default this property is set to `30000 milliseconds`. 
The test is going to take less time to succeed if we reduce this commit interval.
=> Kstream commit interval config

009-quarkus-infinispan-grpc-kafka/README.md, 009-quarkus-infinispan-grpc-kafka/pom.xml, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/grateful/shutdown/SlowTopicConsumer.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/grateful/shutdown/SlowTopicResource.java, 009-quarkus-infinispan-grpc-kafka/src/main/resources/application.properties, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/grateful/shutdown/KafkaGratefulShutdownTest.java
Added a scenario to cover the difference of behaviour when setting the `graceful-shutdown` property for Kafka connectors. 
Note that I could not add a Native scenario because the inject of `LogFile` is not working in this scenario.
=> Scenario for QUARKUS-858:Avoid message loss during the graceful shutdown

022-quarkus-properties-config-all/src/main/java/quarkus/qe/providers/CustomConfigSource.java, 101-javaee-like-getting-started/src/main/java/io/quarkus/qe/core/CustomHealthCheckGroup.java, 101-javaee-like-getting-started/src/test/java/io/quarkus/qe/core/JavaEELikeHealthCheckTest.java, 302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/auth/AuthN.java, 302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/handlers/JWTHandler.java, 302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/services/AbstractRedisDao.java, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/jwt/JwtTest.java, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/web/AbstractCommonTest.java, 303-quarkus-vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/handlers/AirlineHandler.java, 303-quarkus-vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/handlers/AirportsHandler.java, 303-quarkus-vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/handlers/BasketHandler.java, 303-quarkus-vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/handlers/FlightsHandler.java, 303-quarkus-vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/handlers/PricingRulesHandler.java, 303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java, 303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/CommonTestCases.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/BasicsRouteHandler.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/ValidationOnRequestBodyRouteHandler.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/ValidationOnRequestParamsRouteHandler.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/ValidationOnResponseRouteHandler.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnResponseRouteHandlerTest.java, 603-spring-web-smallrye-openapi/src/test/resources/request-types.csv, 603-spring-web-smallrye-openapi/src/test/resources/response-types.csv, pom.xml
Changes:
- Change HttpMethod to use the one from vertx route:
The reactive routes signature have changed and need to use another HttpMethod enum. More info in here: https://github.com/quarkusio/quarkus/commit/72da8546b564aa4871ea16aa4bf5b930f0f9286b
- Regression issue: Infinispan and Kafka extensions stopped working at the same time, reported by https://github.com/quarkusio/quarkus/issues/16386
- The annotation `@Health` got removed. I changed it to `@Readiness`. I've also added a new test case for covering the `HealthGroup` annotation and reported https://github.com/quarkusio/quarkus/issues/16389
- Regression Test: Validation errors on Reactive routes are no longer propagated. Reported by https://github.com/quarkusio/quarkus/issues/16430
- Regression issue: SmallRye OpenAPI generates …
=> Update Beefy TS to Quarkus 2.x (Vertx 4 - 999-SNAPSHOT)

101-javaee-like-getting-started/README.md, 101-javaee-like-getting-started/src/main/java/io/quarkus/qe/core/InjectingScopedBeansResource.java, 101-javaee-like-getting-started/src/test/java/io/quarkus/qe/core/InjectingScopedBeansResourceTest.java, 101-javaee-like-getting-started/src/test/java/io/quarkus/qe/core/NativeInjectingScopedBeansResourceIT.java
Reproducer for https://issues.redhat.com/browse/QUARKUS-662: "Injection of HttpSession throws UnsatisfiedResolutionException during the build phase" is covered by the test `InjectingScopedBeansResourceTest` and `NativeInjectingScopedBeansResourceIT`.
I've confirmed that the module is not building when using a Quarkus release where this issue was not fixed:
```
mvn clean install -Dquarkus.platform.version=1.10.1.Final -Dquarkus-plugin.version=1.10.1.Final
```
=> Reproducer for QUARKUS-662: Injec of HttpSession throws exception

302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/config/VertxAuthObjectMapperCustomizer.java
This module was failing in Native because this exception:
```
{"timestamp":1618384522931,"status":500,"error":"Internal Server Error","path":"/bladeRunner/","message":"Failed to encode as JSON: No serializer found for class io.vertx.ext.auth.impl.UserImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)"}
```
Note that I tried to approach this error following this guide: https://quarkus.io/guides/writing-native-applications-tips#using-the-registerforreflection-annotation
This means that I tried:
- Adding `@RegisterForReflection(targets=UserImpl.class)`
- And adding the `reflection-config.json` file
Any of these two approaches worked, but disabling the failures on empty beans.
=> Fix module 302 in Native

302-quarkus-vertx-jwt/pom.xml, 302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/config/VertxAuthObjectMapperCustomizer.java
- Remove `io.vertx:vertx-auth-common` (not required on Quarkus 2.x)
- Add github issue related to Vertx auth.user serialization error.
=> Remove Vertx unused lib

101-javaee-like-getting-started/README.md, 101-javaee-like-getting-started/src/main/java/io/quarkus/qe/core/InjectingScopedBeansResource.java, 101-javaee-like-getting-started/src/test/java/io/quarkus/qe/core/InjectingScopedBeansResourceTest.java, 101-javaee-like-getting-started/src/test/java/io/quarkus/qe/core/NativeInjectingScopedBeansResourceIT.java
Reproducer for https://issues.redhat.com/browse/QUARKUS-662: "Injection of HttpSession throws UnsatisfiedResolutionException during the build phase" is covered by the test `InjectingScopedBeansResourceTest` and `NativeInjectingScopedBeansResourceIT`.
=> [1.11] Reproducer for QUARKUS-662: Inject of HttpSession throws exception

301-quarkus-vertx-kafka/pom.xml
Update confluent maven repository URL in order to be supported by Maven 3.8.1
=> Maven 3.8.1 doesn't support insecured paths

301-quarkus-vertx-kafka/pom.xml
=> [1.11] Maven 3.8.1 doesn't support insecured paths

304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnRequestBodyRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnRequestParamRouteHandlerTest.java
The issue https://github.com/quarkusio/quarkus/issues/15159 has been resolved in Quarkus upstream, so we can remove the workarounds that force mapping routes to JSON. This verifies that the issue is gone.
=> Remove workaround for Vert.x Routes to map to JSON

603-spring-web-smallrye-openapi/src/test/resources/request-types.csv, 603-spring-web-smallrye-openapi/src/test/resources/response-types.csv
This reverts commit 73621b68466229f736b349eff0e7497f8e1410a4.
Reverts a commit from https://github.com/quarkus-qe/beefy-scenarios/pull/163.
Related issue https://github.com/quarkusio/quarkus/issues/16395 has been resolved in quarkus `main` by https://github.com/quarkusio/quarkus/pull/16546.
=> Revert "Spring Web + Smallrye OpenAPI coverage - failing cases commented out"

006-quartz-manually-scheduled-job/src/main/resources/application.properties
The "db" value has been deprecated as part of https://github.com/quarkusio/quarkus/commit/66a0191ffab01cd5b2c5320756bdbfc94c85314c
=> Replaced deprecated Quartz Store Type to JDBC-CMT

009-quarkus-infinispan-grpc-kafka/pom.xml, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/ConfluentKafkaTestResource.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/StrimziKafkaResource.java, 012-quarkus-kafka-streams/pom.xml, 012-quarkus-kafka-streams/src/test/java/io/quarkus/qe/StrimziKafkaResource.java, 301-quarkus-vertx-kafka/pom.xml, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/resources/ConfluentKafkaResource.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/resources/StrimziKafkaResource.java, pom.xml
- Move on to Kafka 2.7
-   `confluentinc/cp-kafka:6.1.1` is poing to [Kafka 2.7](https://docs.confluent.io/platform/current/installation/versions-interoperability.html)
- Strimzi: `latest-kafka-2.7.0`
- Remove Avro Kafka plugin ([Not required anymore](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#avro))
=> Kafka 2.7 migration

301-quarkus-vertx-kafka/src/main/java/io/quarkus/qe/kafka/consumer/KStockPriceConsumer.java, checkstyle.xml, pom.xml
- Update import rules to validate io packages at the end
- Fix formatter when using Maven profiles
At the moment, it was failing when selecting Maven profiles because the `format` profile was unselected and hence the properties were not present.
- Add Checkstyle to avoid import statements that use the * notation.
=> Update formatter rules to validate `io` packages, avoid import stars and fixed when selecting Maven profiles

.github/workflows/daily.yaml, .github/workflows/pr.yaml, 002-quarkus-all-extensions/pom.xml, 009-quarkus-infinispan-grpc-kafka/pom.xml, 010-quarkus-opentracing-reactive-grpc/pom.xml, 011-quarkus-panache-rest-flyway/pom.xml, 012-quarkus-kafka-streams/pom.xml, 013-quarkus-oidc-restclient/pom.xml, 014-quarkus-panache-with-transactions-xa/pom.xml, 019-quarkus-consul/pom.xml, 021-quarkus-panache-multiple-pus/pom.xml, 300-quarkus-vertx-webClient/pom.xml, 301-quarkus-vertx-kafka/pom.xml, 302-quarkus-vertx-jwt/pom.xml, 303-quarkus-vertx-sql/pom.xml, 602-spring-data-rest/pom.xml
Configured only for:
- PRs (similarly as done for Linux)
- Daily (only graalvm)
- Daily Native: Only the module 003 as build native requires lots of disk space and it was failing with `Error: There is not enough space on the disk.`
Not done for Ecosystem.
=> Configure Github CI to run tests on Windows

009-quarkus-infinispan-grpc-kafka/pom.xml, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/ConfluentKafkaTestResource.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/StrimziKafkaResource.java, 012-quarkus-kafka-streams/pom.xml, 012-quarkus-kafka-streams/src/test/java/io/quarkus/qe/StrimziKafkaResource.java, 301-quarkus-vertx-kafka/pom.xml, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/vertx/kafka/ConfluentKafkaResource.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/vertx/kafka/StrimziKafkaResource.java, pom.xml
backport of #201 
Note: this commit `90f053f` wasn't backported because doesn't apply to version 1.11
=> [1.11] Upgrade to Kafka 2.7

303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/CommonTestCases.java
The issue https://github.com/quarkusio/quarkus/issues/16430 has been fixed in Upstream, so we can verify the fix by uncommenting the test case.
=> Verify fix for quarkus/issues/16430

300-quarkus-vertx-webClient/pom.xml, 300-quarkus-vertx-webClient/src/main/resources/application.properties, 300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceTest.java, 300-quarkus-vertx-webClient/src/test/resources/application.properties
Disabled open telemetry extensions, because is throwing a Random/SplittableRandom
initialized error on build time
Issue Ref: https://github.com/quarkusio/quarkus/issues/17234
=> Open telemetry throw a Random/SplittableRandom initialized error 

022-quarkus-properties-config-all/README.md, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/configmapping/ConfigMappingResource.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/configmapping/Person.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/configmapping/PersonInterface.java, 022-quarkus-properties-config-all/src/main/resources/application.properties, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/configmapping/ConfigMappingResourceTest.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/configmapping/NativeConfigMappingResourceIT.java
Examples are inspired by https://github.com/smallrye/smallrye-config/blob/main/cdi/src/test/java/io/smallrye/config/inject/ConfigMappingInjectionTest.java
More info about this annotation: https://smallrye.io/docs/smallrye-config/mapping/mapping.html
=> Add coverage for `@ConfigMapping` annotation

022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/GreetingResource.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/config/AntagonistConfiguration.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/config/ProtagonistConfiguration.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/config/interfaces/IBiography.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/config/interfaces/ProtagonistConfigurable.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/converter/CustomEmailConverter.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/converter/KrustyEmail.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/providers/CustomConfigSource.java, 022-quarkus-properties-config-all/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource, 022-quarkus-properties-config-all/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/config/VariousConfigurationSourcesTest.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/config/VariousConfigurationSourcesTestIT.java
The proper package name should be `io.quarkus.qe` as the rest of the modules.
=> Rename package from quarkus.qe to io.quarkus.qe

014-quarkus-panache-with-transactions-xa/README.md, 014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MySqlDatabaseTestResource.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MysqlTestProfile.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/dbpool/AgroalPoolTest.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/rest/data/UserResourceTest.java
backport: #203 
On Quarkus 1.11 `AssertSubscriber` object doesn't support await(int amount) so the test was re-written. 
We cover the same scenarios as the main branch except when an end-user requests a connection 3 ms ahead of the expiration time.
=> [1.11] Agroal DB pool test coverage

603-spring-web-smallrye-openapi/src/test/resources/request-types.csv, 603-spring-web-smallrye-openapi/src/test/resources/response-types.csv
This reverts commit 0d3548a848e66f991610a1c0eaa988d528ae71ae.
Backport of https://github.com/quarkus-qe/beefy-scenarios/pull/145.
Do not merge before https://issues.redhat.com/browse/QUARKUS-849 is resolved.
=> [1.11] Revert "Spring Web + Smallrye OpenAPI coverage - failing cases commented out"

023-quarkus-kamelet/README.md, 023-quarkus-kamelet/pom.xml, 023-quarkus-kamelet/src/main/java/io/quarkus/qe/kamelet/KameletResource.java, 023-quarkus-kamelet/src/main/java/io/quarkus/qe/kamelet/KameletRoutes.java, 023-quarkus-kamelet/src/main/resources/application.properties, 023-quarkus-kamelet/src/main/resources/kamelets/fresh-beer-integration-example.groovy, 023-quarkus-kamelet/src/main/resources/kamelets/fresh-beer.Kamelet.yaml, 023-quarkus-kamelet/src/main/resources/kamelets/logger.kamelet.yaml, 023-quarkus-kamelet/src/test/java/io/quarkus/qe/kamelet/KameletIT.java, 023-quarkus-kamelet/src/test/java/io/quarkus/qe/kamelet/KameletTest.java, pom.xml
Quarkus-kamelet provide you support to interacting with Camel routes templates.
The aim of this module is to cover the following Kamelet scenarios:
* Camel producers, those scenarios where your service produces events and are consumed by a camel route
* Camel consumers, those scenarios where your service consumes a camel route
* Chain routes multiples routes
* Load application properties as routes bodies
* Validate Kamelet resources as ocp/k8s kamelet yamls(routes-temapltes, routes-bindings...)
This PR also cover this issue: https://github.com/quarkusio/quarkus/issues/16954
=> Add Kamelet module

020-quarkus-http-non-application-endpoints/src/main/resources/application.properties, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/CommonNonAppEndpoint.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/LegacyNonApplicationEndpointIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/LegacyNonApplicationEndpointTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointNonRootPathTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTest.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTestNonBaseRootPathTest.java
quarkus.http.redirect-to-non-application-root-path deprecated property was removed
This PR removes the deprecated property from test cases and also setup a new scenario where health.root-path is set to "/health" (as used to be in Quarkus 1.7), instead of `/q/health`. This scenario shows up a way to maintain the old endpoint.
=> Legacy non-application endpoint redirection use case

022-quarkus-properties-config-all/pom.xml, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/providers/CustomConfigSource.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeBulkOfPropertiesIT.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeConfigValueIT.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/config/VariousConfigurationSourcesTestIT.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/configmapping/NativeConfigMappingResourceIT.java
Adding external properties on Native make the app fail to start. Reported by https://github.com/quarkusio/quarkus/issues/17653
=> Disable Native tests for module 022  because #quarkus/17653

009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/providers/KafkaProviders.java
This change is related to https://github.com/quarkusio/quarkus/commit/11bc00f324b6ed4166ab4250e6661060b7d1a4d4.
The problem is that keeping injecting the default Kafka broker using `@Named` is now failing:
```java
@ApplicationScoped
public class KafkaProviders {
@Inject
@Named("default-kafka-broker")
Map<String, Object> config;
}
```
Using:
```java
@ApplicationScoped
public class KafkaProviders {
@Inject
@Identifier("default-kafka-broker")
Map<String, Object> config;
}
```
It works. 
Therefore, this is a breaking change that should be noted in the Migration guide for 2.x. Reported by https://github.com/quarkusio/quarkus/issues/17754
=> Fix 009 module to use @Identifier instead of @Named to inject broker

301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/StrimziKafkaIT.java
Kafka failing when using Apicurio registry on Native: https://github.com/quarkusio/quarkus/issues/17829
=> Disable StrimziKafkaIT test on Native because of #quarkus/issues/17829

002-quarkus-all-extensions/pom.xml
The fix was done on AWS SDK which has been integrated in Quarkus 1.13.5.Final and later.
https://github.com/quarkusio/quarkus/issues/15434
=> Remove workaround for Enable tests for quarkus/issues/15434

.github/workflows/pr.yaml, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserRepository.java, 302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/config/AuthNConfig.java
This solution is based on the Jenkins script detection file and uses the https://github.com/marketplace/actions/get-all-changed-files step to get the changes for a PR.
Furthermore, the PR will address a couple of bugs:
- In 014, it will fix a format issue (we should take care of merging PRs with failing actions)
- In 302, the behaviour of `@WithName` has changed in 2.1. I've reported https://github.com/quarkusio/quarkus/issues/18842 to clarify if the new behaviour is correct (I think it is) and to update the migration guide accordingly.
=> Run Native only for the changed modules in PRs

017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/NativeAnnotationScheduledJobsQuartzIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/LegacyNonApplicationEndpointIT.java
These two scenarios are taking more than 1 hour:
```
Time elapsed: 1,088.937 s - in io.quarkus.qe.quartz.NativeAnnotationScheduledJobsQuartzIT
Time elapsed: 1,273.42 s - in io.quarkus.qe.non_application.endpoint.LegacyNonApplicationEndpointIT
```
=> Disable AnnotationScheduledJobsQuartz and LegacyNonApplication on Native

022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/configmapping/ConfigMappingResource.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/configmapping/Person.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/configmapping/ConfigMappingResourceTest.java
Quarkus upstream upgraded SmallRye Config to 2.4.3 and it seems that there is no longer possible to use the annotation @ConfigMapping on classes, only in interfaces.
As we're already covering the interface mapping, I removed the field coverage.
Related issue: quarkusio/quarkus#19298
=> Fix properties module by removing the Person field

020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointNonRootPathIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/NonAppEndpointTestNonBaseRootPathIT.java, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/RelativePathNonAppEndpointIT.java
These tests require to build the app on Native (it's not reusing the native artifact from the target folder).
This coverage is now in the test suite, so it should be fine to disable these tests.
Execution times:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,247.033 s - in io.quarkus.qe.non_application.endpoint.NonAppEndpointIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 287.141 s - in io.quarkus.qe.non_application.endpoint.RelativePathNonAppEndpointIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,236.566 s - in io.quarkus.qe.non_application.endpoint.NonAppEndpointNonRootPathIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 284.907 s - in …
```
=> Disable non application tests on Native due to high execution time

014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/dbpool/AgroalPoolTest.java
Datasource '<default>': JDBC resources leaked: 0 ResultSet(s) and 1 Statement(s)
=> Fix a statement leak resulting in a ton of warnings in the logs

012-quarkus-kafka-streams/src/test/java/io/quarkus/qe/SslAlertMonitorTest.java, pom.xml
At some point, maybe this should be put in a shared constant but it
seems a bit too involved to create a shared module just for that.
=> Separate @QuarkusTest execution

002-quarkus-all-extensions/pom.xml, 300-quarkus-vertx-webClient/pom.xml, 302-quarkus-vertx-jwt/pom.xml, 302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/config/AuthNConfig.java, 303-quarkus-vertx-sql/pom.xml, 304-quarkus-vertx-routes/pom.xml
Issue Ref: 
https://github.com/quarkusio/quarkus/pull/19933
https://github.com/quarkusio/quarkus/pull/20058
- Rename quarkus-vertx-web to quarkus-reactive-routes extensions
- merge the quarkus-vertx and quarkus-vertx-core extentions
=> Remove unnecessary quarkus-vertx-web dependency

002-quarkus-all-extensions/pom.xml, 002-quarkus-all-extensions/src/main/resources/application.properties
- `quarkus-hibernate-orm-rest-data-panache` brings reactive libraries as `quarkus-resteasy-reactive` that has a conflict with other non-reactive libraries that are in the module `002-quarkus-all-extensions`
- Remove Dependency: `io.quarkus:quarkus-vertx` was duplicated
=> Remove `quarkus-hibernate-orm-rest-data-panache` due to a dependency conflict

011-quarkus-panache-rest-flyway/pom.xml, 014-quarkus-panache-with-transactions-xa/pom.xml, 017-quartz-cluster/pom.xml, 602-spring-data-rest/pom.xml, 603-spring-web-smallrye-openapi/pom.xml
The quarkus-hibernate-orm-rest-data-panache and spring web extensions are no longer reactive. This has been reverted in Quarkus main: https://github.com/quarkusio/quarkus/commit/5054ba11db07d7d2a538a989d707ae90bf6ddd36
=> Revert changes related to hibernate-orm-rest-data-panache and spring web

603-spring-web-smallrye-openapi/pom.xml
Additional dep is needed because of decoupling of RestEasy module from quarkus-spring-web
=> Add quarkus-resteasy-jackson dependency for 603-spring-web module

302-quarkus-vertx-jwt/pom.xml
As a result of https://github.com/quarkusio/quarkus/pull/21142,
`io.quarkus:quarkus-jackson` has to be added manually alongside
`io.quarkus:quarkus-vertx` if we want to use
`com.fasterxml.jackson.databind` classes.
In case of `302-quarkus-vertx-jwt`, the
`VertxAuthObjectMapperCustomizer` requires this dependency.
=> Add `quarkus-jackson` alongside `quarkus-vertx`

pom.xml
Native compilation error:
```
`Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/ext/ExceptionMapper`
```
- disable modules `303-quarkus-vertx-sql` and `304-quarkus-vertx-routes` because of this native build image issue: https://github.com/quarkusio/quarkus/issues/21516
=> Comment `303-quarkus-vertx-sql` and `304-quarkus-vertx-routes` due to an issue on hibernate validator

300-quarkus-vertx-webClient/pom.xml, 300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceIT.java, 301-quarkus-vertx-kafka/pom.xml, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeConfluentKafkaIT.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeStrimziKafkaIT.java
Workaround to https://github.com/quarkusio/quarkus/issues/22275.
=> Disable native build in `300-quarkus-vertx-webClient` and `301-quarkus-vertx-kafka` modules

300-quarkus-vertx-webClient/pom.xml, 300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceIT.java, 301-quarkus-vertx-kafka/pom.xml, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeConfluentKafkaIT.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeStrimziKafkaIT.java
Revert "Disable native build in `300-quarkus-vertx-webClient` and `301-quarkus-vertx-kafka` modules"
This reverts commit 58fe6a7e0a2dd2ff4439710c3abc640e719a9b4b.
Issue is fixed in Quarkus 2.6.1.Final
=> Revert "Disable native build in `300-quarkus-vertx-webClient` and `301-quarkus-vertx-kafka` modules"

010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/AbstractPingPongResourceTest.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/containers/JaegerApiEndpointAddress.java, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/containers/JaegerTestResource.java
Use custom marker annotation instead of @ConfigProperty
https://github.com/quarkusio/quarkus/pull/24579 - @ConfigProperty is not intended for integration tests
=> Use custom marker annotation instead of @ConfigProperty

300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceTest.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/KafkaCommonTest.java
Application name is now propagated in JVM tests
Details in https://github.com/quarkusio/quarkus/issues/25097
I first thought there was a bug in Quarkus main, but the change goes in the right direction and we need to update the tests.
=> Application name is now propagated in JVM tests

002-quarkus-all-extensions/src/test/java/io/quarkus/qe/core/containers/MongoTestResource.java, 013-quarkus-oidc-restclient/src/main/resources/application.properties, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/OpenApiTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/OpenApiTestIT.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MySqlDatabaseTestResource.java, 019-quarkus-consul/src/test/java/io/quarkus/qe/containers/ConsulContainer.java, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/resources/RedisResource.java, 303-quarkus-vertx-sql/pom.xml, 303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/test/resources/MysqlResource.java, 303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/test/resources/PostgresqlResource.java, 303-quarkus-vertx-sql/src/test/resources/docker-compose.yaml, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnRequestBodyRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnRequestParamRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnResponseRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationAssertions.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationErrorResponse.java, pom.xml
Today [Bitnami migrated](https://github.com/bitnami-labs/sealed-secrets/issues/822#issuecomment-1104116084) their images to [Dockerhub Bitnami](https://hub.docker.com/u/bitnami). The migration caused several test errors in [beefy-scenarios](https://github.com/quarkus-qe/beefy-scenarios), more specifically:
- `014-quarkus-panache-with-transactions-xa` failed due to missing `quay.io/bitnami/mysql:5.7.32`
- `019-quarkus-consul` failed due to missing `quay.io/bitnami/consul:1.9.3`
- `302-quarkus-vertx-jwt` failed due to missing `quay.io/bitnami/redis:6.0`
- `002-quarkus-all-extensions` failed due to missing `quay.io/bitnami/mongodb:4.0.23`
while I didn't find connect between migration and following failures (so far, there might be correlation between `302-quarkus-vertx-jwt` and other `vertx` …
=> Migrate Bitnami images to the official ones

301-quarkus-vertx-kafka/pom.xml, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeConfluentKafkaIT.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeStrimziKafkaIT.java
Revert "Disable native because of broken opentelemetry-exporter-jaeger"
This reverts commit dabebde178288c6ffbc518a58d427c5b8e63ab23.
https://github.com/quarkusio/quarkus/issues/25143 is fixed now in Quarkus main
=> Revert "Disable native because of broken opentelemetry-exporter-jaeger"

pom.xml
Revert "Disable modules 300 and 301 after grpc version bump (#282)"
This reverts commit 2f424cb50aef696f8d9803e85f1ee5c6635e43a2.
Issue is fixed by https://github.com/quarkusio/quarkus/pull/26132
=> Revert "Disable modules 300 and 301 after grpc version bump (#282)"

302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/Application.java
Two days ago Vert.X were [bumped to 4.3.1](https://github.com/quarkusio/quarkus/pull/26294) that caused errors in CI daily runs. According to the [4.3 release notes](https://vertx.io/blog/whats-new-in-vert-x-4-3/#vertx-web) the handler order matters, I also found similar issue [reported here](https://github.com/vert-x3/vertx-web/issues/2182). Security policy handler `CorsHandler` should be registered after the logging handler.
=> Fix 302-quarkus-vertx-jwt start up by reordering Vert.X Web handler

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Updates GraalVM/Mandrel version to 22.2.
=> Update native image builders - use version 22.2

.github/mvn-settings.xml
Currently, we are compiling Quarkus latest code on Github CI and reusing these bits in the sub-sequence steps of the build.
This PR disables download snapshots from Maven repositories
=> Github CI: disable Snapshot download

.github/workflows/daily.yaml, .github/workflows/pr.yaml
By default native images are going to be built by graalVM/mandrel JDK17
=> Set JDK17 as default native docker image

014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserRepository.java
As part of https://github.com/quarkusio/quarkus/commit/1bd01c45471db6fdd4a5e38b0419c42bf6548f17, we need to switch to a different overriding method, i.e. from `findAll` to `find` method from interface [`PanacheRepositoryBase`](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/PanacheRepositoryBase.java)  as part of the change.
This should be documented on the release notes.
Please select the relevant options.
=> Fix for test classes using REST data panache

.github/dependabot.yml
Adding dependabot to maintain and keep Github actions up to date along with the Maven dependencies.
Please select the relevant options.
=> Add dependabot to the repository for Maven dependencies and GH Actions

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Follows up of https://github.com/quarkus-qe/beefy-scenarios/pull/309
As a [`graalvm/setup-graalvm`](https://github.com/graalvm/setup-graalvm) GHA was introduced, we need to get rid of the non used GHA actions for Windows, as they are now already available when using this GHA
=> Remove non-used GHA for Windows Native build

002-quarkus-all-extensions/src/main/resources/application.properties
Revert "Workaround for redis issue quarkus#29606"
This reverts commit 58e4085f68d12abbe079c72cd6a4d8f71ea940a2.
Upstream got fixed today
=> Revert "Workaround for redis issue quarkus#29606"

.github/workflows/pr.yaml
Fix based on the example https://github.com/tj-actions/changed-files#usage.
=> Fix changed modules detection in PRs and run only necessary CI modules

.github/workflows/pr.yaml
This reverts commit 90938352c7c61bd25a5c9ad41b190d476a6c9405.
Now that I understand the problem, only Quarkus QE Test Suite was affected as this PR workflow does not output changes. I'm very sorry.
=> Revert "Fix changed modules detection in PRs and run only necessary"

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Move to new builder images introduced in Quarkus 2.14
PR with the change - https://github.com/quarkusio/quarkus/pull/27997
NEW is active - https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags
OLD is without update for 3 months - https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags
=> Move to new builder images introduced in Quarkus 2.14

.github/workflows/daily.yaml
Use Java 17 based GraalVM on Windows for Daily
=> Use Java 17 based GraalVM on Windows for Daily

021-quarkus-panache-multiple-pus/src/main/resources/import-fruits.sql, 021-quarkus-panache-multiple-pus/src/main/resources/import-vegetables.sql
Quarkus now defaults to [pooled-lo pool optimizer](https://github.com/quarkusio/quarkus/issues/31899) that avoid unsigned ids, so our workaround does not force ids of newly created rows (that's one created by application logic, not init script) to start right after rows inserted by init script. This PR updates next expected id so that next id is inserted right after the rows inserted by init script.
=> Fix MultiplePersistenceUnitTest by removing workaround that adds a gap of 50 as pool optimizer now uses pooled-lo strategy

020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/LegacyNonApplicationEndpointTest.java
Explicit request uri, REST Assured defaults to app root path
This change starts with https://github.com/quarkusio/quarkus/commit/09fb41167ca41c1a794799f0555d5783b8c8b6fb
I think the change is correct as the application root path should be used by default.
Before the change the Request URI was http://localhost:8081/health
After the change the Request URI is http://localhost:8081/api/health ... includes `/api`
REST Assured defaults to application root path for `QuarkusProdModeTest` now. Checked also standalone app with `@QuarkusTest` and Request URI is http://localhost:8081/api/health including Quarkus 2.16.0.Final. So the https://github.com/quarkusio/quarkus/commit/09fb41167ca41c1a794799f0555d5783b8c8b6fb change fixes the behavior for `QuarkusProdModeTest`.
```properties …
```
=> Explicit request uri, REST Assured defaults to app root path

002-quarkus-all-extensions/pom.xml
Drop neo4j as relocations for Quarkus 1.x extensions were removed
https://github.com/quarkusio/quarkus/tree/main/relocations now covers just the latest changes done for Quarkus 2.x
=> Drop neo4j as relocations were removed

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Add retention-days for storing maven repo artifact (1GB)
The default retention policy is 90 days - https://github.com/actions/upload-artifact#retention-period
=> Add retention-days for maven repo artifact

020-quarkus-http-non-application-endpoints/src/main/resources/application.properties, 020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/openshift/OpenShiftYamlHealthProbesIT.java
Kubernetes resource name no longer depends on container image name
Change was done in https://github.com/quarkusio/quarkus/pull/33724
=> Kubernetes resource name no longer depends on container image name

002-quarkus-all-extensions/pom.xml
The extension has been removed from Quarkus in https://github.com/quarkusio/quarkus/pull/31997.
=> Remove elasticsearch-rest-high-level-client dependency

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Change CI definition from latest mandrel version to specific version (23.0.1.2-Final) as the newest one was built only by JDK 21. This is specific for windows native.
=> Change mandrel version in CI

.github/workflows/daily.yaml, .github/workflows/pr.yaml, .github/workflows/quarkus-snapshot.yaml, 300-quarkus-vertx-webClient/README.md, 301-quarkus-vertx-kafka/README.md, 302-quarkus-vertx-jwt/README.md, 303-quarkus-vertx-sql/README.md, README.md
Quarkus changed, daily fails. See also https://github.com/quarkus-qe/quarkus-test-suite/pull/1556.
=> Move Java baseline to 17

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Bump upload/download-artifact from 3 to 4
https://github.com/actions/download-artifact#breaking-changes
"Downloading artifacts that were created from action/upload-artifact@v3 and below are not supported."
https://github.com/actions/upload-artifact#breaking-changes
"Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error."
=> Bump upload/download-artifact from 3 to 4

002-quarkus-all-extensions/pom.xml, 003-quarkus-many-extensions/pom.xml, 013-quarkus-oidc-restclient/pom.xml, 301-quarkus-vertx-kafka/pom.xml
Move to quarkus-resteasy-client based artifacts
There is big rename going on in Quarkus main / Quarkus 3.9 Let's use the new naming and not rely on relocations which can be deleted any day
002-quarkus-all-extensions fail is unfortunately expected, it's under investigation atm.
It seems that GraalVM upgrade is triggering passing full classpath and it fails on https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/recording/BytecodeRecorderImpl.java#L681 for applications with big classpath, I will file issue for it once I find more details.
=> Move to quarkus-resteasy-client based artifacts

pom.xml
Drop unused Camel Quarkus dependencies
Deps are defined but not used.
=> Drop unused Camel Quarkus dependencies

602-spring-data-rest/src/main/java/org/acme/spring/data/rest/BookRepository.java
Fix Spring Data compilation after Spring bump upstream
After https://github.com/quarkusio/quarkus/pull/40344 compilation of this project fails.
=> Fix Spring Data compilation after Spring bump upstream

021-quarkus-panache-multiple-pus/src/test/java/io/quarkus/qe/multiplepus/containers/MariaDbDatabaseTestResource.java
Use a higher version of MariaDB instead of the default 10.3.6
Fixes CI failure in 021-quarkus-panache-multiple-pus module:
`Caused by: io.quarkus.runtime.configuration.ConfigurationException: Persistence unit 'fruits' was configured to run with a database version of at least '10.6.0', but the actual version is '10.3.0'. Consider upgrading your database. Alternatively, rebuild your application with 'quarkus.datasource."fruits".db-version=10.3.0' (but this may disable some features and/or impact performance negatively).`
root cause: https://github.com/testcontainers/testcontainers-java/blob/main/modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java#L21
`10.11` is used in https://github.com/quarkusio/quarkus/blob/main/build-parent/pom.xml#L93
=> Use a higher version of MariaDB instead of the default 10.3.6

300-quarkus-vertx-webClient/pom.xml
By recent change https://github.com/quarkusio/quarkus/pull/41816 some old realocation were droped. The `quarkus-opentelemetry-exporter-otlp ` is not managed by `quarkus-bom`. By message this happend in 2.14 and [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.14#opentelemetry-exporters-moved) mention it as well
=> Remove quarkus-opentelemetry-exporter-otlp 

002-quarkus-all-extensions/src/test/java/io/quarkus/qe/core/AlmostAllQuarkusExtensionsTest.java, 004-quarkus-HHH-and-HV/README.md, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/validator/TestResources.java, 006-quartz-manually-scheduled-job/src/test/java/io/quarkus/qe/quartz/TestResources.java, 011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/AbstractPingPongResourceTest.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/MySqlApplicationResourceTest.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/rest/data/UserResourceTest.java, 017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/AnnotationScheduledJobsQuartzTest.java, 019-quarkus-consul/src/test/java/io/quarkus/qe/GreetingResourceTest.java, 021-quarkus-panache-multiple-pus/src/test/java/io/quarkus/qe/multiplepus/MultiplePersistenceUnitTest.java, 300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceTest.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/ConfluentKafkaTest.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/StrimziKafkaTest.java, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/web/BladeRunnerHandlerTest.java, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/web/NoSecuredResourceTest.java, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/web/ReplicantHandlerTest.java, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/vertx/web/SecuredResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/TestResources.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/TestResources.java
Updating deprecated @QuarkusTestResource to @WithTestResource as it's new in 3.13.0 https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.13#quarkustestresource-replaced-by-withtestresource-gear-white_check_mark
=> Update deprecated `@QuarkusTestResource` to `@WithTestResource`

015-quarkus-micrometer/pom.xml
Use `quarkus-micrometer-registry-prometheus` instead of direct `io.micrometer:micrometer-registry-prometheus` usage
=> Use quarkus-micrometer-registry-prometheus

002-quarkus-all-extensions/pom.xml, 003-quarkus-many-extensions/pom.xml, 301-quarkus-vertx-kafka/README.md, 301-quarkus-vertx-kafka/pom.xml
This PR fixes the daily. These artifacts were renamed in Quarkus 3.9
=> Change Quarkus reactive messaging artifact names

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Reduces log heaviness. Adds `--batch-mode --no-transfer-progress` for maven execution to reduce "Downloading ...." messages
=> Reduce log size in CI runs by suppressing download transfer progress

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Same situation as here https://github.com/quarkus-qe/quarkus-test-suite/pull/2153, please check it out for context.
=> Raise native image Xmx to 7g in GitHub workflows testing native mode as build-time RSS increased due to upstream changes

.github/workflows/daily.yaml, .github/workflows/pr.yaml, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/items/ItemsResourceTest.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBeanResourceTest.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/validator/JakartaPersistenceAndHibernateValidatorResourceTest.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/validator/TestResources.java, 006-quartz-manually-scheduled-job/src/test/java/io/quarkus/qe/quartz/TestResources.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/BookResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/TestResources.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/di/SpringDiTest.java
There was a bug in `TestResourceScope.MATCHING_RESOURCES` which made this work and was fixed in https://github.com/quarkusio/quarkus/pull/44279, I change it in this PR https://github.com/quarkus-qe/beefy-scenarios/pull/505 but it seems I wrongy understand the docs back then.
Not it should work as:
* `RESTRICTED_TO_CLASS` start for every test class, every test class need anotation
* `MATCHING_RESOURCES` start for specific group of test classes, every test class need anotation
* `GLOBAL` start for every test class, only one annotation
I change it to cover all 3 usages.
=> Fix and refactor the scope of some resources

013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/clients/TokenPropagationPongClient.java
Change io.quarkus.oidc.token.propagation.AccessToken to io.quarkus.oidc.token.propagation.common.AccessToken
io.quarkus.oidc.token.propagation.AccessToken was deprecated since 3.19 and removed for 3.28
https://github.com/quarkusio/quarkus/pull/49667
=> Change io.quarkus.oidc.token.propagation.AccessToken to io.quarkus.oidc.token.propagation.common.AccessToken

003-quarkus-many-extensions/src/main/resources/application.properties
This reverts commit 2ca52351ab051b968359833b5da931e056f785d6 as the usptream issue was fixed
=> Enable ORM for 003-quarkus-many-extensions
