quarkus-qe/beefy-scenarios

.github/workflows/daily.yaml, .github/workflows/pr.yaml
GitHub Actions for PRs and daily builds
Fixes https://github.com/quarkus-qe/beefy-scenarios/issues/4
=> GitHub Actions for PRs and daily builds

.github/workflows/daily.yaml
Use quarkus.native.container-build
=> Use quarkus.native.container-build

.github/workflows/daily.yaml, 002-quarkus-all-extensions/src/main/resources/application.properties
- Use equal sing in application.properties
- Native build - use jdk8 and jdk11 native builder images
=>  Native build - use jdk8 and jdk11 native builder images  ++ use equal sing in application.properties

002-quarkus-all-extensions/pom.xml, 003-quarkus-many-extensions/pom.xml
- Comment out oauth2 extension as it colides with JWT expensio
- Removing artemis-jms from many-extensions case
=> oauth2 and artemis-jms changes

004-quarkus-HHH-and-HV/pom.xml, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/validator/Hello.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/validator/Human.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/validator/JpaAndHibernateValidatorResource.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/validator/SomeChildEntity.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/validator/SomeEntity.java, 004-quarkus-HHH-and-HV/src/main/resources/META-INF/resources/index.html, 004-quarkus-HHH-and-HV/src/main/resources/application.properties, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/validator/JpaAndHibernateValidatorResourceTest.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/validator/NativeJpaAndHibernateValidatorResourceIT.java, Jenkinsfile, pom.xml
Scenario for Hibernate and Hibernate Validator with lazy fetch strategy
=> Scenario for Hibernate and Hibernate Validator with lazy fetch strategy

pom.xml
Reorder properties definition
Mainly to see GH actions in action, there were some failures
=> Reorder properties definition

005-quarkus-and-maven-profiles/pom.xml, 005-quarkus-and-maven-profiles/src/main/java/io/quarkus/qe/core/QuarkusAndMavenProfilesResource.java, 005-quarkus-and-maven-profiles/src/main/resources/META-INF/resources/index.html, 005-quarkus-and-maven-profiles/src/main/resources/application.properties, 005-quarkus-and-maven-profiles/src/test/java/io/quarkus/qe/core/NativeQuarkusAndMavenProfilesIT.java, 005-quarkus-and-maven-profiles/src/test/java/io/quarkus/qe/core/QuarkusAndMavenProfilesTest.java, pom.xml
Quarkus and Maven profiles scenario
Quarkus Maven plugin does a lot of work on it's own and it is good to check that properties get propagated and artifacts from custom repositories gets pulled and used.
=> Quarkus and Maven profiles

.github/workflows/daily.yaml, 004-quarkus-HHH-and-HV/pom.xml, 004-quarkus-HHH-and-HV/src/main/resources/application.properties, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/validator/TestResources.java, Jenkinsfile
Enable 004-quarkus-HHH-and-HV in native mode
H2 is no longer embedded in tested application but executed next to it via `H2DatabaseTestResource`
=> Enable 004-quarkus-HHH-and-HV in native mode

601-spring-data-primitive-types/pom.xml, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/Book.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/Cat.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/NamedEntity.java, 601-spring-data-primitive-types/src/main/resources/application.properties, 601-spring-data-primitive-types/src/main/resources/import.sql, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/BookResourceIT.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/BookResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceIT.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/TestResources.java, README.md, pom.xml
Spring Data module with tests for primitive types for custom query
Additional coverage for https://github.com/quarkusio/quarkus/issues/9192
Covering also long case and boolean for both primitive and object case
=> Spring Data module with tests for primitive types for custom query

README.md
Tip for LargeStaticResourceTest - testBigFileAvailability failure
=> Tip for LargeStaticResourceTest - testBigFileAvailability failure

201-large-static-content/src/test/java/io/quarkus/qe/content/GenerateLargeFile.java
=> Close RandomAccessFile object

201-large-static-content/src/test/java/io/quarkus/qe/content/GenerateLargeFile.java
Use try-with-resources in GenerateLargeFile
=> Use try-with-resources in GenerateLargeFile

.github/workflows/daily.yaml
Move to ubi-quarkus-native-image 20.1.0 based images
=>  Move to ubi-quarkus-native-image 20.1.0 based images

.github/workflows/daily.yaml
Daily CI action to run JVM mode on both 8 and 11, Native using 11
There is GraalVM JDK 8 native-image issue discussed on quarkusio/quarkus: Issue #6717
=> Daily CI action to run JVM mode on both 8 and 11, Native using 11

.github/workflows/daily.yaml
=> Add Mandrel to daily CI

.github/workflows/daily.yaml
Move to ubi-quarkus-mandrel 20.1.0.1.Final image
=> Move to ubi-quarkus-mandrel 20.1.0.1.Final image

002-quarkus-all-extensions/README.md, 002-quarkus-all-extensions/pom.xml, 002-quarkus-all-extensions/src/main/resources/application.properties, 002-quarkus-all-extensions/src/test/java/io/quarkus/qe/core/AlmostAllQuarkusExtensionsTest.java, 002-quarkus-all-extensions/src/test/java/io/quarkus/qe/core/NativeAlmostAllQuarkusExtensionsIT.java
Adding new extensions from Quarkus 1.7
=> Adding new extensions from Quarkus 1.7

201-large-static-content/src/test/java/io/quarkus/qe/content/GenerateLargeFile.java
Use 512 MB file in 201-large-static-content
=> Use 512 MB file in 201-large-static-content

002-quarkus-all-extensions/README.md
Example for extensions check between Quarkus 1.7 and Quarkus 1.8
=> Example for extensions check between Quarkus 1.7 and Quarkus 1.8

002-quarkus-all-extensions/pom.xml, 002-quarkus-all-extensions/src/main/resources/application.properties
Once https://github.com/quarkusio/quarkus/pull/12051 is in, we can merge this PR.
=> Quarkus 1.9 updates

.github/workflows/daily.yaml
GH Actions - update images, drop Java 8
=> GH Actions - update images, drop Java 8

.github/workflows/daily.yaml
601-spring-data-primitive-types/.factorypath
=> Fix native build in GH Actions

008-infinispan-getting-started/README.md, 008-infinispan-getting-started/pom.xml, 008-infinispan-getting-started/src/main/java/org/acme/quickstart/GreetingResource.java, 008-infinispan-getting-started/src/main/java/org/acme/quickstart/InfinispanClientApp.java, 008-infinispan-getting-started/src/main/resources/META-INF/hotrod-client.properties, 008-infinispan-getting-started/src/main/resources/application.properties, 008-infinispan-getting-started/src/test/java/org/acme/quickstart/CacheResource.java, 008-infinispan-getting-started/src/test/java/org/acme/quickstart/InfinispanServerResourceTest.java, 008-infinispan-getting-started/src/test/java/org/acme/quickstart/NativeInfinispanServerResourceIT.java, README.md, pom.xml
Test that Infinispan client pick up the hotrod-client.properties file in the build time
=> Add test Infinispan client can read hotrod-client.properties file

README.md
A bit more details for Scenarios IDs
=> A bit more details for Scenarios IDs

011-quarkus-panache-rest-flyway/README.md, 011-quarkus-panache-rest-flyway/pom.xml, 011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ApplicationEntity.java, 011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ApplicationResource.java, 011-quarkus-panache-rest-flyway/src/main/resources/application.properties, 011-quarkus-panache-rest-flyway/src/main/resources/db/migration/V1.0.0__init.sql, 011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/NativePostgreSqlApplicationResourceIT.java, 011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java, 011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/containers/PostgreSqlDatabaseTestResource.java, pom.xml
Added new module to cover Hibernate ORM and Flyway modules.
Note that my idea is to cover more databases in the future.
=> Added Panache-Flyway example

011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/containers/PostgreSqlDatabaseTestResource.java, 300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceTest.java
=> Minor cleanup in the code

.github/workflows/daily.yaml
Missing space after mvn-settings.xml
=> Missing space after mvn-settings.xml

.github/mvn-settings.xml, .github/workflows/daily.yaml, .github/workflows/pr.yaml
Using google-maven-central for beefy-scenarios build
=> Using google-maven-central for beefy-scenarios build

013-quarkus-oidc-restclient/README.md, 013-quarkus-oidc-restclient/pom.xml, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/LookupAuthorizationPingResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/PingResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/ReactivePingResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/clients/LookupAuthorizationPongClient.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/clients/PongClient.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/clients/ReactivePongClient.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/pong/PongResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/pong/ReactivePongResource.java, 013-quarkus-oidc-restclient/src/main/resources/application.properties, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/AbstractPingPongResourceTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/LookupAuthorizationRestPingPongResourceTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/NativeLookupAuthorizationRestPingPongResourceIT.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/NativeReactivePingPongResourceIT.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/NativeRestPingPongResourceIT.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/ReactivePingPongResourceTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/RestPingPongResourceTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/containers/KeycloakTestResource.java, 013-quarkus-oidc-restclient/src/test/resources/test-realm.json, pom.xml
Module that covers the RestClient and OIDC integration using Keycloak container.
There are two applications:
- Ping application that will invoke the Pong application using the RestClient and will return the expected "ping pong" output.
- Pong application that will return the "pong" output.
=> Added module OIDC with RestClient

.github/mvn-settings.xml, .github/workflows/daily.yaml, .github/workflows/pr.yaml, 009-quarkus-infinispan-grpc-kafka/README.md, 009-quarkus-infinispan-grpc-kafka/pom.xml, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/books/Book.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/books/BookCacheInitializer.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/books/BookContextInitializer.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/books/BookResource.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/GreetingResource.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/HelloService.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/prices/PriceConsumer.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/prices/PriceConverter.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/prices/PriceGenerator.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/prices/PriceResource.java, 009-quarkus-infinispan-grpc-kafka/src/main/proto/helloworld.proto, 009-quarkus-infinispan-grpc-kafka/src/main/resources/application.properties, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/books/BookServiceTest.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/books/NativeBookServiceIT.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/InfinispanTestResource.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/KafkaTestResource.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/greeting/GreetingServiceTest.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/greeting/NativeGreetingServiceIT.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/prices/NativePriceServiceIT.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/prices/PriceServiceTest.java, pom.xml
Cherry-pick from master to add test coverage for: https://issues.redhat.com/browse/QUARKUS-541
=> Cherry-pick from master: Added grpc, infinispan and kafka coverage

014-quarkus-panache-with-transactions-xa/README.md, 014-quarkus-panache-with-transactions-xa/pom.xml, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/ApplicationEntity.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/ApplicationResource.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/DataSourceResource.java, 014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/MySqlApplicationResourceTest.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/NativeMySqlApplicationResourceIT.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MySqlDatabaseTestResource.java, pom.xml
Added a module that test whether we can setup a REST API using ORM Panache and a multi-tenant data source configuration with Agroal extension and MySQL database.
These changes verify https://issues.redhat.com/browse/QUARKUS-549.
=> Added mysql and panache

014-quarkus-panache-with-transactions-xa/README.md, 014-quarkus-panache-with-transactions-xa/pom.xml, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/ApplicationEntity.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/ApplicationResource.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/DataSourceResource.java, 014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/MySqlApplicationResourceTest.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/NativeMySqlApplicationResourceIT.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MySqlDatabaseTestResource.java, pom.xml
Related PR in Master: https://github.com/quarkus-qe/beefy-scenarios/pull/59
=> Backport for 1.7: Added mysql with XA transactions and panache

302-quarkus-vertx-jwt/README.md, 302-quarkus-vertx-jwt/pom.xml, 302-quarkus-vertx-jwt/src/test/java/io/quarkus/qe/JwtTest.java, pom.xml
In the future, there will be a complete security scenario with Quarkus + Vert.x and JWT tokens
TD for https://issues.redhat.com/browse/QUARKUS-579
=> Add test development for JWT token x5c

009-quarkus-infinispan-grpc-kafka/pom.xml, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/GreetingResource.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/MutinyHelloService.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/greeting/GreetingServiceTest.java
gRPC supports both blocking and non-blocking (mutiny) approaches. We had implemented only the blocking scenario. In this PR, we're covering the non-blocking one.
=> Infinispan gRPC Kafka: Add mutiny gRPC service

601-spring-data-primitive-types/README.md, 601-spring-data-primitive-types/pom.xml, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/BookResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatRepository.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/HttpCommonsHeaders.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/SessionResource.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/AppConfiguration.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/CounterBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/InstanceIdBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/RequestIdBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/configuration/SessionIdBean.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Address.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Animal.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Book.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Cat.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Mammal.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/NamedEntity.java, 601-spring-data-primitive-types/src/main/resources/import.sql, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/BookResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersIT.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java
=> Backport for 1.7: Feature/spring beans and jpa issues

.github/workflows/daily.yaml
=> Bump GraalVM/Mandrel to 20.3

.github/workflows/daily.yaml, .github/workflows/pr.yaml
* Update ubi-quarkus-native-image in GH actions
* Add native smoke test into PR flow
Fixes failure in daily GH Action run.
=> Update ubi-quarkus-native-image in GH actions, add native smoke test into PR flow

001-quarkus-getting-started/README.md, 002-quarkus-all-extensions/src/main/resources/application.properties, 003-quarkus-many-extensions/pom.xml, 003-quarkus-many-extensions/src/main/resources/application.properties, 004-quarkus-HHH-and-HV/README.md, 004-quarkus-HHH-and-HV/src/main/resources/application.properties, 005-quarkus-and-maven-profiles/README.md, 006-quartz-manually-scheduled-job/README.md, 007-openshift-yaml-health-probes/README.md, 008-infinispan-getting-started/README.md, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/KafkaTestResource.java, 011-quarkus-panache-rest-flyway/README.md, 013-quarkus-oidc-restclient/src/main/resources/application.properties, 014-quarkus-panache-with-transactions-xa/README.md, 101-javaee-like-getting-started/README.md, 201-large-static-content/README.md, 300-quarkus-vertx-webClient/src/main/java/io/quarkus/qe/vertx/webclient/config/VertxWebClientConfig.java, 301-quarkus-vertx-kafka/src/main/java/io/quarkus/qe/vertx/kafka/config/VertxKProducerConfig.java
Enrich module's description/add README
Plus small fixes applied
P.S. Let me know if it's better to create separate PR for README files and fixes
=> Update modules description and refactor

013-quarkus-oidc-restclient/README.md, 013-quarkus-oidc-restclient/pom.xml, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/AutoAcquireTokenPingResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/TokenPropagationPingResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/clients/AutoAcquireTokenPongClient.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/clients/TokenPropagationPongClient.java, 013-quarkus-oidc-restclient/src/main/resources/application.properties, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/AutoAcquireTokenPingPongResourceTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/NativeAutoAcquireTokenPingPongResourceIT.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/NativeTokenPropagationPingPongResourceIT.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/TokenPropagationPingPongResourceTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/containers/KeycloakTestResource.java, 013-quarkus-oidc-restclient/src/test/resources/test-realm.json
Added some scenarios with the new OIDC Client Filter/Token propagation extensions.
=> Add scenarios for OIDC Filter and Token Propagation

006-quartz-manually-scheduled-job/src/main/java/io/quarkus/qe/quartz/AnnotationScheduledCounter.java, 006-quartz-manually-scheduled-job/src/main/java/io/quarkus/qe/quartz/ManuallyScheduledCounter.java, 006-quartz-manually-scheduled-job/src/main/java/io/quarkus/qe/quartz/services/CounterService.java, 006-quartz-manually-scheduled-job/src/test/java/io/quarkus/qe/quartz/QuartzTestCase.java
Updated existing Quartz scenario to inject services via CDI and invoke `@PostConstruct`.
=> Update quartz scenario to inject services into tasks

pom.xml
Bump testcontainers-bom from 1.15.1 to 1.15.2
=> Bump testcontainers-bom from 1.15.1 to 1.15.2

304-quarkus-vertx-routes/README.md, 304-quarkus-vertx-routes/pom.xml, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/BasicsRouteHandler.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/Request.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/Response.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/ValidationOnRequestBodyRouteHandler.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/ValidationOnRequestParamsRouteHandler.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/ValidationOnResponseRouteHandler.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/annotations/Uppercase.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/annotations/UppercaseService.java, 304-quarkus-vertx-routes/src/main/java/io/quarkus/qe/validation/annotations/UppercaseValidator.java, 304-quarkus-vertx-routes/src/main/resources/application.properties, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/BasicsRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/NativeValidationOnRequestBodyRouteHandlerIT.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/NativeValidationOnRequestParamRouteHandlerIT.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/NativeValidationOnResponseRouteHandlerIT.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnRequestBodyRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnRequestParamRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/ValidationOnResponseRouteHandlerTest.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationAssertions.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationError.java, 304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationErrorResponse.java, pom.xml
This module covers some basic scenarios around reactive routes in general and also:
- Validation on request params, request body and responses.
=> Add new module for vertx and routes

602-spring-data-rest/README.md, 602-spring-data-rest/pom.xml, 602-spring-data-rest/src/main/java/org/acme/spring/data/rest/Book.java, 602-spring-data-rest/src/main/java/org/acme/spring/data/rest/BookRepository.java, 602-spring-data-rest/src/main/java/org/acme/spring/data/rest/Library.java, 602-spring-data-rest/src/main/java/org/acme/spring/data/rest/LibraryRepository.java, 602-spring-data-rest/src/main/resources/application.properties, 602-spring-data-rest/src/main/resources/import.sql, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/BookRepositoryTest.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/LibraryRepositoryTest.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/NativeBookRepositoryTestIT.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/NativeLibraryRepositoryTestIT.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/containers/PostgreSqlDatabaseTestResource.java, pom.xml
Test development for quarkus-spring-data rest extension.
Please take a look at Hibernate Validator, if there is a mistake from my side as it returns HTTP 500 on verification (should be 400 as it's a client's data inconsistency)
Verified in native mode
=> Add test for quarkus-spring-data-rest extension

.github/workflows/daily.yaml
Disable running with Mandrel because of graalvm/mandrel #218
=> Disable running with Mandrel because of graalvm/mandrel #218

017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/AnnotationScheduledJobsQuartzTest.java, 017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/NativeAnnotationScheduledJobsQuartzIT.java, 017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/resources/QuartzNodeApplicationResource.java, 017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/resources/TestResources.java, pom.xml
- Usage of start() method from QuarkusProdModeTest
- Add native test for quartz-cluster
=> Refactor quartz-cluster module and added Native test

014-quarkus-panache-with-transactions-xa/pom.xml, 014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties
Added a temporal workaround for fixing Panache test. This is caused by this issue https://github.com/quarkusio/quarkus/issues/15369.
Also, the module name and the folder name didn't match. This is also addressed as part of this PR.
=> Add workaround for panache test

.github/workflows/quarkus-snapshot.yaml
We need to add this workflow before registering our repository into Quarkus Ecosystem.
=> Added quarkus ecosystem workflow

.github/workflows/daily.yaml, .github/workflows/pr.yaml
=> GH Actions - run all tests

013-quarkus-oidc-restclient/README.md, 013-quarkus-oidc-restclient/pom.xml, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/TokenPropagationPingResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/ping/clients/TokenPropagationPongClient.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/NativeTokenPropagationPingPongResourceIT.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/TokenPropagationPingPongResourceTest.java
The issue https://github.com/quarkusio/quarkus/issues/14466 has been fixed, so this PR is about to enable the tests for this coverage.
=> Enable tests to cover access token (new oidc token propagation module)

009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/books/Book.java, 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/books/BookServiceTest.java, 011-quarkus-panache-rest-flyway/README.md, 011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ApplicationEntity.java, 011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java, 602-spring-data-rest/src/main/java/org/acme/spring/data/rest/BookRepository.java, 602-spring-data-rest/src/main/java/org/acme/spring/data/rest/LibraryRepository.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/BookRepositoryTest.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/LibraryRepositoryTest.java, 602-spring-data-rest/src/test/java/org/acme/spring/data/rest/NativeLibraryRepositoryTestIT.java
Affected modules:
- Panache
- Spring Data
Found this other issue: https://github.com/quarkusio/quarkus/issues/15492
=> Updates after adding basic exception handling in REST services

020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/CommonNonAppEndpoint.java
Add swagger-ui to non-appliaction endpoint test
=> Add swagger-ui to non-appliaction endpoint test

019-quarkus-consul/src/test/java/io/quarkus/qe/GreetingResourceTest.java, 019-quarkus-consul/src/test/java/io/quarkus/qe/NativeGreetingResourceIT.java
=> bugfix: Native test are running on JVM mode

013-quarkus-oidc-restclient/src/main/resources/application.properties, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/AbstractPingPongResourceTest.java
Cherrypick of https://github.com/quarkus-qe/beefy-scenarios/pull/127
=> Add timeouts for Module 013

017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/NativeAnnotationScheduledJobsQuartzIT.java, 017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/resources/ApplicationResource.java
Quartz Native test are running on JVM mode
=> bugfix: Quartz Native test are running on JVM mode

004-quarkus-HHH-and-HV/README.md, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Account.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Customer.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Item.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/ItemsResource.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/items/Role.java, 004-quarkus-HHH-and-HV/src/main/resources/application.properties, 004-quarkus-HHH-and-HV/src/main/resources/import.sql, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/items/ItemsResourceTest.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/items/NativeItemsResourceIT.java
Backport of https://github.com/quarkus-qe/beefy-scenarios/pull/125
=> [1.11] Updated module 004 module to reproduce data loss issues

014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties
Remove the workaround we introduced for https://github.com/quarkusio/quarkus/issues/15369
=> [master] Remove workaround for issue 15369: multiple transactions for update

017-quartz-cluster/src/main/resources/application.properties, 017-quartz-cluster/src/test/resources/common.properties
This issue is related to https://github.com/quarkusio/quarkus/issues/15754.
++ I've added a 1s check interval to let Quartz recover more quickly.
=> Quartz module: Remove start mode forced

020-quarkus-http-non-application-endpoints/src/test/java/io/quarkus/qe/non_application/endpoint/BackwardCompatibilityTest.java
RootPath + Non-application-path should be redirected to /q/non-application-path
=> RootPath + Non-application-path should be redirected to /q/

.github/ci-prerequisites.sh, .github/workflows/daily.yaml, .github/workflows/pr.yaml
Claim some extra disk space to GH in order to avoid errors like :
```
❌ Docker environment should have more than 2GB free disk space
```
=> GH claim disk space

.github/workflows/daily.yaml
Reclaim disk space for native daily build too
=> Reclaim disk space for native daily build too

017-quartz-cluster/src/main/resources/application.properties, 017-quartz-cluster/src/test/resources/common.properties
Backport of https://github.com/quarkus-qe/beefy-scenarios/pull/140
=> [1.11] Quartz module: Remove start mode forced

004-quarkus-HHH-and-HV/README.md, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBean.java, 004-quarkus-HHH-and-HV/src/main/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBeanResource.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/transaction/NativeTransactionScopeBeanResourceIT.java, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBeanResourceTest.java
Backport of https://github.com/quarkus-qe/beefy-scenarios/pull/144
=> [1.11] Added reproducer for QUARKUS-661

.github/workflows/daily.yaml, .github/workflows/pr.yaml, pom.xml
Update Quarkus to 1.11.6 and remove build of Quarkus master from Actions
=> Update Quarkus to 1.11.6 and remove build of Quarkus master from Actions

002-quarkus-all-extensions/pom.xml
The issue https://github.com/quarkusio/quarkus/issues/15442 has been fixed. 
I've verified that without the fix, it was failing and with the fix now it works.
=> Remove workaround for issue 15442

603-spring-web-smallrye-openapi/README.md, 603-spring-web-smallrye-openapi/pom.xml, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/persistence/model/Book.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/persistence/repo/BookRepository.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/BookController.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/RestExceptionHandler.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/SimpleController.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/exception/BookIdMismatchException.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/exception/BookNotFoundException.java, 603-spring-web-smallrye-openapi/src/main/resources/application.properties, 603-spring-web-smallrye-openapi/src/main/resources/templates/home.html, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/BookResourceTest.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/HomePageTest.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/NativeBookResourceIT.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/NativeHomePageIT.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/TestResources.java
Based on https://github.com/eugenp/tutorials/tree/master/spring-boot-modules/spring-boot-bootstrap.
Adopting process tracked in https://github.com/jsmrcka/tutorials/tree/quarkus-spring-web.
Related to https://issues.redhat.com/browse/QUARKUS-185.
Unresolved issue: https://github.com/quarkusio/quarkus/issues/16321
=> New spring-web scenario

022-quarkus-properties-config-all/README.md, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/bulk/BulkOfPropertiesConfiguration.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/bulk/BulkOfPropertiesResource.java, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/bulk/ConfigValueResource.java, 022-quarkus-properties-config-all/src/main/resources/application.properties, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/BulkOfPropertiesTest.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/ConfigValueTest.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeBulkOfPropertiesIT.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeConfigValueIT.java
These are two new features in MicroProfile 4.0.
See more in https://microprofile.io/2020/12/23/microprofile-4-0-is-now-available/
=> Cover Bulk Injection of Properties and ConfigValue instances

.github/workflows/quarkus-snapshot.yaml
Allow manual trigger for ecosystem CI
=> Allow manual trigger + remove branch reference for ecosystem CI

101-javaee-like-getting-started/README.md, 101-javaee-like-getting-started/src/main/java/io/quarkus/qe/core/FallbackResource.java, 101-javaee-like-getting-started/src/test/java/io/quarkus/qe/core/FallbackResourceTest.java, 101-javaee-like-getting-started/src/test/java/io/quarkus/qe/core/NativeFallbackResourceIT.java
The MP Fault Tolerance API adds metrics using the MP Metrics API.
This scenario covers this integration in Quarkus using Fallback.
=> Added coverage for Fallback and metrics

013-quarkus-oidc-restclient/README.md, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/secured/SecuredResource.java, 013-quarkus-oidc-restclient/src/main/java/io/quarkus/qe/tokens/TokenProviderResource.java, 013-quarkus-oidc-restclient/src/main/resources/application.properties, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/secured/SecuredResourceTest.java
Added:
- Secured endpoints to return the claim data
- Token generator endpoint to provide tokens using the OIDC Client
=> Added claims coverage

603-spring-web-smallrye-openapi/README.md, 603-spring-web-smallrye-openapi/pom.xml, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/persistence/model/Book.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/persistence/repo/BookRepository.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/BookController.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/RestExceptionHandler.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/SimpleController.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/exception/BookIdMismatchException.java, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/exception/BookNotFoundException.java, 603-spring-web-smallrye-openapi/src/main/resources/application.properties, 603-spring-web-smallrye-openapi/src/main/resources/templates/home.html, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/BookResourceTest.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/HomePageTest.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/NativeBookResourceIT.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/NativeHomePageIT.java, 603-spring-web-smallrye-openapi/src/test/java/io/quarkus/qe/books/TestResources.java
https://github.com/quarkus-qe/beefy-scenarios/pull/162
=> [1.11] New spring-web scenario

601-spring-data-primitive-types/README.md, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/Account.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AccountService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AccountServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AudioBookService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AudioBookServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AuthorService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AuthorServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/BookService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/BookServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/PersonDao.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/PersonDaoImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/SpringBeansConfig.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/SpringMainConfig.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/SpringPersonService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/UserService.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/di/SpringDiTest.java
Based on https://github.com/eugenp/tutorials/tree/master/spring-di.
Adopting process tracked in https://github.com/jsmrcka/tutorials/commits/quarkus-spring-di, originally https://github.com/rsvoboda/tutorials/commits/experiments.
Related to https://issues.redhat.com/browse/QUARKUS-184.
=> Add new spring-di scenario

601-spring-data-primitive-types/README.md, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/Account.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AccountService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AccountServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AudioBookService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AudioBookServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AuthorService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/AuthorServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/BookService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/BookServiceImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/PersonDao.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/PersonDaoImpl.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/SpringBeansConfig.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/SpringMainConfig.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/SpringPersonService.java, 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/di/UserService.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/di/SpringDiTest.java
https://github.com/quarkus-qe/beefy-scenarios/pull/179
=> [1.11] Add new spring-di scenario

014-quarkus-panache-with-transactions-xa/README.md, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserEntity.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserRepository.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserResource.java, 014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties, 014-quarkus-panache-with-transactions-xa/src/main/resources/import.sql, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/rest/data/UserResourceTest.java
This work is part of https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-976.md effort
=> Add test coverage for rest-data-with-panache repositories

014-quarkus-panache-with-transactions-xa/README.md, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserEntity.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserRepository.java, 014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserResource.java, 014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties, 014-quarkus-panache-with-transactions-xa/src/main/resources/import.sql, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/rest/data/UserResourceTest.java
This work is part of https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-976.md effort
Cherry-pick of https://github.com/quarkus-qe/beefy-scenarios/pull/188
=> [1.11] Add test coverage for rest-data-with-panache repositories

009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/BlockingHelloService.java, 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/MutinyHelloService.java, 010-quarkus-opentracing-reactive-grpc/src/main/java/io/quarkus/qe/pong/GrpcPongService.java
As part of https://github.com/quarkusio/quarkus/pull/16830, Quarkus is validating that gRPC services are annotated with `@GrpcService`.
=> Fix gRPC tests

014-quarkus-panache-with-transactions-xa/README.md, 014-quarkus-panache-with-transactions-xa/src/main/resources/application.properties, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MySqlDatabaseTestResource.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MysqlTestProfile.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/dbpool/AgroalPoolTest.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/rest/data/UserResourceTest.java
- Add some test coverage in order to double-check Agroal DB pool management.
=> Agroal DB pool test coverage

300-quarkus-vertx-webClient/src/main/resources/application.properties, 300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceIT.java
=> [1.11] Add debug native symbols generation test

023-quarkus-kamelet/README.md, 023-quarkus-kamelet/pom.xml, 023-quarkus-kamelet/src/main/java/io/quarkus/qe/kamelet/KameletResource.java, 023-quarkus-kamelet/src/main/java/io/quarkus/qe/kamelet/KameletRoutes.java, 023-quarkus-kamelet/src/main/resources/application.properties, 023-quarkus-kamelet/src/main/resources/kamelets/fresh-beer-integration-example.groovy, 023-quarkus-kamelet/src/main/resources/kamelets/fresh-beer.Kamelet.yaml, 023-quarkus-kamelet/src/main/resources/kamelets/logger.kamelet.yaml, 023-quarkus-kamelet/src/test/java/io/quarkus/qe/kamelet/KameletIT.java, 023-quarkus-kamelet/src/test/java/io/quarkus/qe/kamelet/KameletTest.java, pom.xml
=> [1.11] Add kamelet module

.github/workflows/daily.yaml, .github/workflows/pr.yaml
=> [1.11]Compile quarkus with mvnw in CI

022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeBulkOfPropertiesIT.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeConfigValueIT.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/config/VariousConfigurationSourcesTestIT.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/configmapping/NativeConfigMappingResourceIT.java
The issue https://github.com/quarkusio/quarkus/issues/17653 has been fixed, so we can enable the tests back.
I confirmed that these tests are now working fine.
=> Enable tests for quarkus/issues/17653

pom.xml
Quarkus Kamelet doesn't exist in Quarkus Kamelet 1.6
=> Disable Kamelet module

014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/dbpool/AgroalPoolTest.java
Due to a conflict in internal reporting tools, we decided to replace `repeatedTest` JUnit annotation by a loop
=> Replace repeatedTest annotation by a loop

010-quarkus-opentracing-reactive-grpc/src/main/resources/application.properties, 010-quarkus-opentracing-reactive-grpc/src/test/java/io/quarkus/qe/containers/JaegerTestResource.java, 300-quarkus-vertx-webClient/src/test/java/io/quarkus/qe/vertx/webclient/resources/JaegerContainer.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/resources/JaegerContainer.java
These 3 tests were constantly failing because of the Jaeger collector docker container
=> Wait for Jaeger container to be ready

014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserRepository.java, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/rest/data/UserResourceTest.java
Remove workaround.
Feature Implemented: https://github.com/quarkusio/quarkus/issues/16871
=> Panache sort is already implemented

022-quarkus-properties-config-all/README.md, 022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/bulk/BindMapsUsingConfigValueResource.java, 022-quarkus-properties-config-all/src/main/resources/application.properties, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/BindMapsUsingConfigValueTest.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeBindMapsUsingConfigValueIT.java
This use case is now possible thanks to https://github.com/quarkusio/quarkus/issues/17269.
=> Add coverage to inject maps using the @ConfigProperty annotation

.github/workflows/pr.yaml, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/OpenApiTest.java, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/OpenApiTestIT.java
Fix OpenApi tests due to quarkusio/quarkus/pull/19148
=>  Fix OpenApi tests due to quarkusio/quarkus/pull/19148

011-quarkus-panache-rest-flyway/pom.xml, 014-quarkus-panache-with-transactions-xa/pom.xml, 014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/MySqlApplicationResourceTest.java, 017-quartz-cluster/pom.xml, 602-spring-data-rest/pom.xml
This change is caused by https://github.com/quarkusio/quarkus/issues/19875 which as far I understood, it's not going to be reverted or fixed.
Guides updates in https://github.com/quarkusio/quarkus/pull/19995
=> Adapt main to Quarkus 999-SNAPSHOT

002-quarkus-all-extensions/pom.xml, 002-quarkus-all-extensions/src/main/resources/application.properties, 003-quarkus-many-extensions/pom.xml, 003-quarkus-many-extensions/src/main/java/io/quarkus/qe/many/extensions/ManyExtensionsResource.java, 603-spring-web-smallrye-openapi/pom.xml, 603-spring-web-smallrye-openapi/src/main/java/io/quarkus/qe/books/web/SimpleController.java
- Disabled DevServices for all extensions module
- Comment Quarkus-SpringWeb extension due to some reactive library conflicts
- patch some other modules in order to fix dependency conflicts
=> Conflicts between reactive and non-reactive libraries

022-quarkus-properties-config-all/src/main/java/io/quarkus/qe/bulk/BulkOfPropertiesResource.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/BulkOfPropertiesTest.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeBulkOfPropertiesIT.java
Similar to https://github.com/quarkus-qe/quarkus-test-suite/pull/343
=> Workaround in 022-properties module for #issues/20610

017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/AnnotationScheduledJobsQuartzTest.java
Two-node cluster test behaved unpredictably, because
a cluster executes a scheduled trigger randomly all over
its nodes. The original test expected only one node being
fired while both were running.
=> Make Quartz scheduling test more robust

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Include relocations in Quarkus main build
=> Include relocations in Quarkus main build

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Use GraalVM 21.3
Should help with daily CI jobs
=> Use GraalVM 21.3

302-quarkus-vertx-jwt/src/main/java/io/quarkus/qe/vertx/web/services/AbstractRedisDao.java
Multi.collectItems was dropped in latest Mutiny
=> Multi.collectItems was dropped in latest Mutiny

pom.xml
Assertj is no longer present in Quarkus BOM
=> Assertj is no longer present in Quarkus BOM

.github/workflows/pr.yaml, 002-quarkus-all-extensions/pom.xml, 003-quarkus-many-extensions/pom.xml, 101-javaee-like-getting-started/pom.xml
Deprecated quarkus-undertow-websockets was removed
=> Deprecated quarkus-undertow-websockets was removed

301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/resources/SchemaRegistryContainer.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/resources/StrimziKafkaResource.java, pom.xml
Updates to reflect Strimzi related changes in Quarkus main
=> Updates to reflect Strimzi related changes in Quarkus main

006-quartz-manually-scheduled-job/src/main/resources/db/migration/V2.0.0__QuarkusQuartz.sql, 017-quartz-cluster/src/main/resources/db/migration/V1.0.0__init.sql, 017-quartz-cluster/src/main/resources/db/migration/V2.0.0__QuarkusQuartz.sql
Update CREATE SEQUENCE syntax for DB migration scripts
Fixes daily runs with Quarkus main
=> Update CREATE SEQUENCE syntax for DB migration scripts

301-quarkus-vertx-kafka/pom.xml, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeConfluentKafkaIT.java, 301-quarkus-vertx-kafka/src/test/java/io/quarkus/qe/kafka/NativeStrimziKafkaIT.java
Add quarkus-confluent-registry-avro to 301-quarkus-vertx-kafka
(to make build / tests pass)
=> Add quarkus-confluent-registry-avro to 301-quarkus-vertx-kafka

pom.xml
Bump CQ version to avoid failures in native
=> Bump CQ version to avoid failures in native

pom.xml
Disable modules 300 and 301 after grpc version bump
Upstream issues is filed (#26083)
=> Disable modules 300 and 301 after grpc version bump

019-quarkus-consul/pom.xml
Explicit definition of jsoup dependency
Workaround for https://github.com/quarkiverse/quarkus-config-extensions/issues/70
=> Explicit definition of jsoup dependency

019-quarkus-consul/pom.xml, pom.xml
Update Consul extension to 1.1.0
Includes fix for https://github.com/quarkiverse/quarkus-config-extensions/issues/70
=> Update Consul extension to 1.1.0

022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/ConfigValueTest.java, 022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/NativeConfigValueIT.java
Update test expectation in native mode
=> Update 022-quarkus-properties-config scenario due to an upstream changes

pom.xml
Related to: https://github.com/quarkusio/quarkus/issues/28007
=> Disable Kamelet module due to a Quarkus/Upstream issue

.github/workflows/daily.yaml, .github/workflows/pr.yaml
=> Bump used GH actions

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Follows up https://github.com/quarkus-qe/beefy-scenarios/pull/307
Updating below github actions:
From `DeLaGuardo/setup-graalvm@master` to `graalvm/setup-graalvm@v1`
From `jitterbit/get-changed-files@v1` to `tj-actions/changed-files@v34.4.3`
=> Follow-up regarding GH Actions updates

002-quarkus-all-extensions/src/main/resources/application.properties
Workaround for redis issue https://github.com/quarkusio/quarkus/issues/29606
=> Workaround for redis issue quarkus#29606

015-quarkus-micrometer/src/test/java/io/quarkus/qe/HttpServerMetricsTest.java, 015-quarkus-micrometer/src/test/java/io/quarkus/qe/UsingMicroProfilePingPongResourceTest.java
Micrometer - trailing comma is no longer present, quarkusio/quarkus#30343
=> Micrometer - trailing comma is no longer present, quarkusio/quarkus#30343

017-quartz-cluster/src/main/resources/db/migration/V1.0.0__init.sql, 017-quartz-cluster/src/test/java/io/quarkus/qe/quartz/AnnotationScheduledJobsQuartzTest.java
Fixes Quartz tests, Multiple-pus is still work in progress
=> Fix tests failing due to update to Hibernate 6

021-quarkus-panache-multiple-pus/src/main/resources/application.properties, 021-quarkus-panache-multiple-pus/src/main/resources/import-fruits.sql, 021-quarkus-panache-multiple-pus/src/main/resources/import-vegetables.sql, 021-quarkus-panache-multiple-pus/src/test/java/io/quarkus/qe/multiplepus/containers/MariaDbDatabaseTestResource.java, 021-quarkus-panache-multiple-pus/src/test/java/io/quarkus/qe/multiplepus/containers/PostgreSqlDatabaseTestResource.java
Follow up to https://github.com/quarkus-qe/beefy-scenarios/pull/363
=> Fix tests which are failing due to update to Hibernate 6

.github/workflows/quarkus-snapshot.yaml
Fix setup-java for Quarkus ecosystem CI
=> Fix setup-java for Quarkus ecosystem CI

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Hi, same fix as [https://github.com/quarkus-qe/quarkus-jdkspecifics/pull/94](https://github.com/quarkus-qe/quarkus-jdkspecifics/pull/94)
=> Add installation of pigz to gh action definition.

.github/workflows/daily.yaml, .github/workflows/pr.yaml
Switch GitHub Actions to Mandrel 23 and relevant GraalVM
=> Switch GitHub Actions to Mandrel 23 and relevant GraalVM

603-spring-web-smallrye-openapi/src/test/resources/request-types.csv
Disable checks related to https://github.com/quarkusio/quarkus/issues/36297
=> Disable checks related to https://github.com/quarkusio/quarkus/issues/36297

022-quarkus-properties-config-all/src/test/java/io/quarkus/qe/bulk/ConfigValueTest.java
Switch to DefaultValuesConfigSource after quarkusio/quarkus#35322
=> Switch to DefaultValuesConfigSource after quarkusio/quarkus#35322

303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/test/resources/Db2Resource.java, 303-quarkus-vertx-sql/src/test/resources/docker-compose.yaml
Updating the db2 images as this is old version and it's from custom quay.io image repository.
=> Update db2 images

014-quarkus-panache-with-transactions-xa/src/test/java/io/quarkus/qe/containers/MySqlDatabaseTestResource.java, 303-quarkus-vertx-sql/src/test/resources/docker-compose.yaml
Update docker image of MySQL as 5.7 reach EOL in October
=> Switch MySQL 5.7 to 8 as 5.7 is EOL

011-quarkus-panache-rest-flyway/pom.xml, 303-quarkus-vertx-sql/pom.xml
Dependency addition needed by Flyway 10
=> Dependency addition needed by Flyway 10

013-quarkus-oidc-restclient/pom.xml, 022-quarkus-properties-config-all/pom.xml, 024-quarkus-extension-with-many-classes-to-register/deployment/pom.xml, 024-quarkus-extension-with-many-classes-to-register/runtime/pom.xml, 301-quarkus-vertx-kafka/pom.xml, pom.xml
Switch to quarkus.native.enabled property
Note: https://github.com/quarkusio/quarkus/issues/39669 is fixed now
=> Switch to quarkus.native.enabled property

303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/test/resources/Db2Resource.java
Change DB2 container image
Should resolve fails in https://github.com/quarkus-qe/beefy-scenarios/actions/workflows/daily.yaml
Details in https://hub.docker.com/r/ibmcom/db2
=> Change DB2 container image

301-quarkus-vertx-kafka/src/main/resources/application.properties
Use dereference-schema=true as workaround for quarkus #42504 issue
=> Use dereference-schema=true as workaround for quarkus #42504 issue

.github/workflows/daily.yaml, .github/workflows/pr.yaml, 004-quarkus-HHH-and-HV/src/test/java/io/quarkus/qe/hibernate/validator/TestResources.java, 006-quartz-manually-scheduled-job/src/test/java/io/quarkus/qe/quartz/TestResources.java, 013-quarkus-oidc-restclient/pom.xml, 013-quarkus-oidc-restclient/src/main/resources/application.properties, 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/AbstractPingPongResourceTest.java, 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/TestResources.java
As there is now work on `@WithTestResource` annotation, there were change of behavioral in https://github.com/quarkusio/quarkus/pull/42852. This PR should fix our daily CI.
=> Change parameters for WithTestResource annotation

002-quarkus-all-extensions/src/test/java/io/quarkus/qe/core/containers/KeycloakTestResource.java, 003-quarkus-many-extensions/src/test/java/io/quarkus/qe/many/extensions/containers/KeycloakTestResource.java
Bumping Keycloak to 26.0 as upstream bumped it as well
=> Bump Keycloak to 26.0
